### ISSUE TITLE
[parquet-scrooge] mvn eclipse:eclipse fails on parquet-scrooge

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1402]
`mvn eclipse:eclipse` on the parquet-mr project fails when it hits the scrooge sub-project. Scrooge being in scala, this is probably not very surprising but it means the target doesn't get to all the Hive stuff and Tools. We should at least skip it, if this isn't easy to fix.

**Reporter**: [Dmitriy V. Ryaboy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dvryaboy) / @dvryaboy
**Assignee**: [Dmitriy V. Ryaboy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dvryaboy) / @dvryaboy

<sub>**Note**: *This issue was originally created as [PARQUET-8](https://issues.apache.org/jira/browse/PARQUET-8). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Dmitriy V. Ryaboy](https://issues.apache.org/jira/browse/PARQUET-8?#comment-14039975) / @dvryaboy:
Stack trace:

```Java
[ERROR] Failed to execute goal com.twitter:scrooge-maven-plugin:3.9.0:compile (thrift-sources) on project parquet-scrooge: Execution thrift-sources of goal com.twitter:scrooge-maven-plugin:3.9.0:compile failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.twitter:scrooge-maven-plugin:3.9.0:compile (thrift-sources) on project parquet-scrooge: Execution thrift-sources of goal com.twitter:scrooge-maven-plugin:3.9.0:compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution thrift-sources of goal com.twitter:scrooge-maven-plugin:3.9.0:compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 23 more
Caused by: java.lang.NullPointerException
	at com.twitter.AbstractMavenScroogeMojo.findThriftDependencies(AbstractMavenScroogeMojo.java:324)
	at com.twitter.AbstractMavenScroogeMojo.findThriftFiles(AbstractMavenScroogeMojo.java:292)
	at com.twitter.AbstractMavenScroogeMojo.execute(AbstractMavenScroogeMojo.java:191)
	at com.twitter.MavenScroogeCompileMojo.execute(MavenScroogeCompileMojo.java:22)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 24 more
```

**Comment by asfimport** [comment]
[Masayuki Takahashi](https://issues.apache.org/jira/browse/PARQUET-8?#comment-14107994) / @masayuki038:
I had faced the exact same issue. This is a bug in com.twitter:scrooge-maven-plugin:3.9.0. Upgraded to 3.9.2, mvn:eclipse:eclipse was successful.

**Comment by asfimport** [comment]
[Dmitriy V. Ryaboy](https://issues.apache.org/jira/browse/PARQUET-8?#comment-14108221) / @dvryaboy:
Well that was easy, thanks @masayuki038. 
https://github.com/apache/incubator-parquet-mr/pull/41

**Comment by asfimport** [comment]
[Dmitriy V. Ryaboy](https://issues.apache.org/jira/browse/PARQUET-8?#comment-14114331) / @dvryaboy:
HEAD is now at f089bac... trivial change to retrigger travis build.
Deleting local branch PR_TOOL_MERGE_PR_41
Deleting local branch PR_TOOL_MERGE_PR_41_MASTER
Pull request #41 merged!
Merge hash: 7a105068
