### ISSUE TITLE
parquet file created via pyarrow 0.4.0 ; version 1.0 - incompatible with Spark

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1492]
using spark sql unable to read parquet file and shows null values. whereas hive reads the values fine.

17/06/19 17:50:36 WARN CorruptStatistics: Ignoring statistics because created_by could not be parsed (see PARQUET-251): parquet-cpp version 1.0.0
org.apache.parquet.VersionParser$VersionParseException: Could not parse created_by: parquet-cpp version 1.0.0 using format: (.+) version ((.**) )?\(build ?(.**)\)
                at org.apache.parquet.VersionParser.parse(VersionParser.java:112)
                at org.apache.parquet.CorruptStatistics.shouldIgnoreStatistics(CorruptStatistics.java:60)

**Reporter**: [Ashima Sood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ash_26)

<sub>**Note**: *This issue was originally created as [PARQUET-1036](https://issues.apache.org/jira/browse/PARQUET-1036). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1036?#comment-16056144) / @wesm:
Could you please post an example file or other way to reproduce the issue? The output you posted is a warning and doesn't seem like it should affect the results

**Comment by asfimport** [comment]
[Ashima Sood](https://issues.apache.org/jira/browse/PARQUET-1036?#comment-16056358):
17/06/20 13:07:50 INFO FileSourceStrategy: Pruning directories with: 
17/06/20 13:07:50 INFO FileSourceStrategy: Post-Scan Filters: 
17/06/20 13:07:50 INFO FileSourceStrategy: Output Data Schema: struct<DATE: binary, ROW_ID: binary, STATUS: binary, GEN_TIME: binary, GEN_MONTH: binary ... 109 more fields>
17/06/20 13:07:50 INFO FileSourceStrategy: Pushed Filters: 
17/06/20 13:07:50 INFO deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
17/06/20 13:07:50 INFO deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
17/06/20 13:07:50 INFO deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
17/06/20 13:07:50 INFO deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
17/06/20 13:07:50 INFO deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
17/06/20 13:07:50 INFO SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
17/06/20 13:07:50 ERROR FileFormatWriter: Aborting job null.
org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
Exchange RoundRobinPartitioning(1)
+- FileScan parquet [DATE#0,ROW_ID#1,STATUS#2,GEN_TIME#3,GEN_MONTH#4.....,... 109 more fields] Batched: false, Format: Parquet, Location: InMemoryFileIndex[file:/<<<<filePath>>>>>..., PartitionFilters: [], PushedFilters: [], ReadSchema: struct<DATE:binary,ROW_ID:binary,STATUS:binary,GEN_TIME:binary,GEN_M...

	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange.doExecute(ShuffleExchange.scala:112)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:87)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:87)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply$mcV$sp(FileFormatWriter.scala:127)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:121)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:121)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:121)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:101)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:87)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:87)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:492)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:198)
	at org.apache.spark.sql.DataFrameWriter.json(DataFrameWriter.scala:473)
	at com.fmrco.mdm.utils.SparkUtil.saveJSONFile(SparkUtil.java:145)
	at com.fmrco.mdm.utils.SparkUtil.SaveToFileFormat(SparkUtil.java:632)
	at com.fmrco.mdm.utils.SparkUtil.loadFileSrcData(SparkUtil.java:486)
	at com.fmrco.mdm.spark.framework.Framework.processJob(Framework.java:31)
	at com.fmrco.mdm.app.MDMApp.main(MDMApp.java:88)
Caused by: org.apache.spark.sql.AnalysisException: Attribute name "Unnamed: 110" contains invalid character(s) among " ,;{}()\n\t=". Please use alias to rename it.;
	at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaConverter$.checkConversionRequirement(ParquetSchemaConverter.scala:581)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaConverter$.checkFieldName(ParquetSchemaConverter.scala:567)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaConverter$$anonfun$checkFieldNames$1.apply(ParquetSchemaConverter.scala:575)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaConverter$$anonfun$checkFieldNames$1.apply(ParquetSchemaConverter.scala:575)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetSchemaConverter$.checkFieldNames(ParquetSchemaConverter.scala:575)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.buildReader(ParquetFileFormat.scala:306)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.buildReaderWithPartitionValues(ParquetFileFormat.scala:291)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD$lzycompute(DataSourceScanExec.scala:253)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD(DataSourceScanExec.scala:251)
	at org.apache.spark.sql.execution.FileSourceScanExec.doExecute(DataSourceScanExec.scala:286)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange.prepareShuffleDependency(ShuffleExchange.scala:85)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:121)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:112)
	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
	... 35 more

**Comment by asfimport** [comment]
[Ashima Sood](https://issues.apache.org/jira/browse/PARQUET-1036?#comment-16056366):
Also, when using spark-sql on unix. the results returned are as below:

spark-sql> select \* from <table> limit 5;
17/06/20 19:53:58 INFO SparkSqlParser: Parsing command: select \* from <table> limit 5
17/06/20 19:53:58 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 10.107.206.68:40150 in memory (size: 2.1 KB, free: 413.9 MB)
17/06/20 19:53:58 INFO BlockManagerInfo: Removed broadcast_0_piece0 on ip-10-107-206-78.fmrco.com:33367 in memory (size: 2.1 KB, free: 2.8 GB)
17/06/20 19:53:58 INFO ContextCleaner: Cleaned accumulator 0
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:53:58 INFO CatalystSqlParser: Parsing command: string
17/06/20 19:54:00 INFO FileSourceStrategy: Pruning directories with:
17/06/20 19:54:00 INFO FileSourceStrategy: Post-Scan Filters:
17/06/20 19:54:00 INFO FileSourceStrategy: Output Data Schema: struct<date: string, row_id: string, status: string, gen_time: string, gen_month: string ... 108 more fields>
17/06/20 19:54:00 INFO FileSourceStrategy: Pushed Filters:
17/06/20 19:54:00 WARN Utils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.debug.maxToStringFields' in SparkEnv.conf.
17/06/20 19:54:00 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 350.8 KB, free 413.6 MB)
17/06/20 19:54:00 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 31.9 KB, free 413.6 MB)
17/06/20 19:54:00 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.107.206.68:40150 (size: 31.9 KB, free: 413.9 MB)
17/06/20 19:54:00 INFO SparkContext: Created broadcast 1 from processCmd at CliDriver.java:376
17/06/20 19:54:00 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4194304 bytes, open cost is considered as scanning 4194304 bytes.
17/06/20 19:54:00 INFO SparkContext: Starting job: processCmd at CliDriver.java:376
17/06/20 19:54:00 INFO DAGScheduler: Got job 1 (processCmd at CliDriver.java:376) with 1 output partitions
17/06/20 19:54:00 INFO DAGScheduler: Final stage: ResultStage 1 (processCmd at CliDriver.java:376)
17/06/20 19:54:00 INFO DAGScheduler: Parents of final stage: List()
17/06/20 19:54:00 INFO DAGScheduler: Missing parents: List()
17/06/20 19:54:00 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[6] at processCmd at CliDriver.java:376), which has no missing parents
17/06/20 19:54:00 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 18.8 KB, free 413.5 MB)
17/06/20 19:54:00 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 7.5 KB, free 413.5 MB)
17/06/20 19:54:00 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.107.206.68:40150 (size: 7.5 KB, free: 413.9 MB)
17/06/20 19:54:00 INFO SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:996
17/06/20 19:54:00 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[6] at processCmd at CliDriver.java:376)
17/06/20 19:54:00 INFO YarnScheduler: Adding task set 1.0 with 1 tasks
17/06/20 19:54:00 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, ip-10-107-206-78.fmrco.com, executor 1, partition 0, RACK_LOCAL, 6573 bytes)
17/06/20 19:54:00 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on ip-10-107-206-78.fmrco.com:33367 (size: 7.5 KB, free: 2.8 GB)
17/06/20 19:54:01 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on ip-10-107-206-78.fmrco.com:33367 (size: 31.9 KB, free: 2.8 GB)
17/06/20 19:54:05 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 4476 ms on ip-10-107-206-78.fmrco.com (executor 1) (1/1)
17/06/20 19:54:05 INFO YarnScheduler: Removed TaskSet 1.0, whose tasks have all completed, from pool
17/06/20 19:54:05 INFO DAGScheduler: ResultStage 1 (processCmd at CliDriver.java:376) finished in 4.477 s
17/06/20 19:54:05 INFO DAGScheduler: Job 1 finished: processCmd at CliDriver.java:376, took 4.518839 s
NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL
NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL
NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL
NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL
NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULLNULL     NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL
Time taken: 6.702 seconds, Fetched 5 row(s)
17/06/20 19:54:05 INFO CliDriver: Time taken: 6.702 seconds, Fetched 5 row(s)

**Comment by asfimport** [comment]
[Ashima Sood](https://issues.apache.org/jira/browse/PARQUET-1036?#comment-16056370):
<FolderPath> is where the .parquet exists
here's the hql for the same: 
CREATE EXTERNAL TABLE IF NOT EXISTS tableName(
  DATE STRING
, ROW_ID STRING
, STATUS STRING
, GEN_TIME STRING
, GEN_MONTH STRING
..
..
..
)
STORED AS PARQUET
LOCATION 's3://${hiveconf:DATA_BUCKET}/<FolderPath>/'
tblproperties ('parquet.compress'='SNAPPY');

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1036?#comment-16056372) / @wesm:
The version of Spark you are using does not support spaces in column names. You need to normalize the column names on the Python side. So this isn't an Arrow or Parquet bug I don't think

**Comment by asfimport** [comment]
[Antoine Pitrou](https://issues.apache.org/jira/browse/PARQUET-1036?#comment-17307922) / @pitrou:
There hasn't been any feedback on this for 4 years, so I'm going to close this. If a similar issue arises, please don't hesitate to open a new JIRA with fresh information.
