### ISSUE TITLE
Parquet-cli is broken after TransCompressionCommand was added

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1600]
<u>Scenario</u>

Run parquet-cli
```java

java -cp 'target/*:target/dependency/*' org.apache.parquet.cli.Main
```
 

<u>Expected result</u> 

parquet-cli usage is presented
```java

Usage: parquet [options] [command] [command options]
```
 

<u>Actual result</u>

the following error is presented
```java

Exception in thread "main" com.beust.jcommander.ParameterException: Only one @Parameter with no names attribute is allowed, found:com.beust.jcommander.JCommander$MainParameter@6442b0a6 and com.beust.jcommander.Parameterized@f5bfa59d
        at com.beust.jcommander.JCommander.addDescription(JCommander.java:606)
        at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:587)
        at com.beust.jcommander.JCommander.addCommand(JCommander.java:1533)
        at com.beust.jcommander.JCommander.addCommand(JCommander.java:1512)
        at org.apache.parquet.cli.Main.<init>(Main.java:95)
        at org.apache.parquet.cli.Main.main(Main.java:181)
```
 

<u>Notes</u>

The error is related to the recent changes in PARQUET-1872.

The fix is trivial - see PR.

**Reporter**: [Grisha Weintraub](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=grishaw) / @grishaw
**Assignee**: [Grisha Weintraub](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=grishaw) / @grishaw

<sub>**Note**: *This issue was originally created as [PARQUET-1910](https://issues.apache.org/jira/browse/PARQUET-1910). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Grisha Weintraub](https://issues.apache.org/jira/browse/PARQUET-1910?#comment-17191699) / @grishaw:
[~shangx@uber.com] Can you please have a look at this ticket/PR?

It's related to PARQUET-1872.
