### ISSUE TITLE
DeprecatedParquetInputFormat in CombineFileInputFormat throw NPE when the first sub-split is empty

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1609]
A followup of PARQUET-1947, after the fix, when the first sub-split is empty in CombineFileInputFormat, there's a NPE:
```Java

Caused by: java.lang.NullPointerException
	at org.apache.parquet.hadoop.mapred.DeprecatedParquetInputFormat$RecordReaderWrapper.next(DeprecatedParquetInputFormat.java:154)
	at org.apache.parquet.hadoop.mapred.DeprecatedParquetInputFormat$RecordReaderWrapper.next(DeprecatedParquetInputFormat.java:73)
	at cascading.tap.hadoop.io.CombineFileRecordReaderWrapper.next(CombineFileRecordReaderWrapper.java:70)
	at org.apache.hadoop.mapred.lib.CombineFileRecordReader.next(CombineFileRecordReader.java:58)
	at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.moveToNext(MapTask.java:199)
	at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.next(MapTask.java:185)
	at cascading.tap.hadoop.util.MeasuredRecordReader.next(MeasuredRecordReader.java:61)
	at org.apache.parquet.cascading.ParquetTupleScheme.source(ParquetTupleScheme.java:160)
	at cascading.tuple.TupleEntrySchemeIterator.getNext(TupleEntrySchemeIterator.java:163)
	at cascading.tuple.TupleEntrySchemeIterator.hasNext(TupleEntrySchemeIterator.java:136)
	... 10 more
```

The reason is CombineFileInputFormat will use the result of createValue of the first sub-split as the value container. Since the first sub-split is empty, the value container is null.

**Reporter**: [Daniel Dai](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daijy) / @daijyc
**Assignee**: [Daniel Dai](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daijy) / @daijyc

<sub>**Note**: *This issue was originally created as [PARQUET-1963](https://issues.apache.org/jira/browse/PARQUET-1963). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Daniel Dai](https://issues.apache.org/jira/browse/PARQUET-1963?#comment-17268907) / @daijyc:
Thanks @gszadovszky!
