### ISSUE TITLE
parquet-cli unable to read UUID values

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1641]
I am finding that parquet-cli throws when trying to read UUID values. 

Attached to this bug report is a parquet file with 2 columns, message encoded as byte-array and number encoded as fixed length byte array (UUID). This file was written by my .net implementation of parquet specification. The file has one row worth of data and is readable by parquet-cpp.

<u>Schema as read by parquet-cli:</u>

message root

{   required binary Message (STRING);   required fixed_len_byte_array(16) Number (UUID); }

<u>Values as read by parquet-cpp:</u>

— Values —
Message                       |Number                        |
First record                  |215 48 212 219 218 57 169 67 166 116 7 79 44 227 50 17 |

 

<u>Here is the exception stack from parquet-cli when trying to read uuid values:</u>
```java

Caused by: org.apache.parquet.io.ParquetDecodingException: The requested schema is not compatible with the file schema. incompatible types: required binary Number (STRING) != required fixed_len_byte_array(16) Number (UUID)
        at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.incompatibleSchema(ColumnIOFactory.java:101)
        at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.visit(ColumnIOFactory.java:93)
        at org.apache.parquet.schema.PrimitiveType.accept(PrimitiveType.java:602)
        at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.visitChildren(ColumnIOFactory.java:83)
        at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.visit(ColumnIOFactory.java:57)
        at org.apache.parquet.schema.MessageType.accept(MessageType.java:55)
        at org.apache.parquet.io.ColumnIOFactory.getColumnIO(ColumnIOFactory.java:162)
        at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:135)
        at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:225)
 
```
 I debugged parquet-cli code and found that parquet-cli is trying to project the UUID as a string and later on that throws as these types are not compatible? 

 

<u>Source code references:</u>

At AvroReadSupport.java, line 97

~~~~~~~~~~~~

    String requestedProjectionString = configuration.get(AVRO_REQUESTED_PROJECTION);

    if (requestedProjectionString != null)

{       Schema avroRequestedProjection = new Schema.Parser().parse(requestedProjectionString);       projection = new AvroSchemaConverter(configuration).convert(avroRequestedProjection);     }

~~~~~~~~~~~~

 

<u>Debugger values for</u>

requestedProjectionString=

{"type":"record","name":"root","fields":[
{"name":"Message","type":"string"}

,\{"name":"Number","type":{"type":"string","logicalType":"uuid"}}]}

[Note that `Number` now has a type of `string` and a logicalType of `uuid`]

 

At ColumnIOFactory.java line 93

~~~~~~~~~~~~

incompatibleSchema(primitiveType, currentRequestedType);

~~~~~~~~~~~~

<u>Debugger values for</u> 

primitiveType = required fixed_len_byte_array(16) Number (UUID)

currentRequestedType = required binary Number (STRING)

 

and this will throw.

 

If I skip over the projection code in AvroReadSupport, parquet-cli is able to read my file.

I am not sure if the bug is in parquet-cli or parquet-mr or in the library I used to encode this file. The fact that parquet-cpp is able to read it gives me some confidence to say that the problem is either in parquet-cli or parquet-mr.

Please point me in the right direction if I could verify this UUID roundtripping purely from parquet-mr itself in form of an unit-test. Happy to contribute tests or fix if needed.

**Reporter**: [Balaji K](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gamaken)
#### Original Issue Attachments:
- [guid.parquet](https://issues.apache.org/jira/secure/attachment/13042816/guid.parquet)

<sub>**Note**: *This issue was originally created as [PARQUET-2140](https://issues.apache.org/jira/browse/PARQUET-2140). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17526736) / @theosib-amazon:
I'll look at this on Monday. Have you tried writing the same parquet data from the Java implementation? Then we can compare the two files at a binary level. There are some things that are legal that the Java implementation doesn't handle so well. It may be that your C# is legal but that for the Java code to understand it, you have to do some slightly different legal thing.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17527480) / @theosib-amazon:
I can't reproduce this bug with parquet-tools or 1.12.0 or 1.13.0-SNAPSHOT.

I have a program that does nothing but read the schema and records out of a parquet file. Here's what I get:

`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - RecordReader initialized will read a total of 1 records.`
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - at row 0. reading next block`
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - block read in memory in 25 ms. row count = 1`
`{`
`  "type" : "record",`
`  "name" : "root",`
`  "fields" : [ {`
`    "name" : "Message",`
`    "type" : "string"`
`  }, {`
`    "name" : "Number",`
`    "type" : {`
`      "type" : "string",`
`      "logicalType" : "uuid"`
`    `}
`  } ]`
``}
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - RecordReader initialized will read a total of 1 records.`
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - at row 0. reading next block`
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - block read in memory in 2 ms. row count = 1`
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - RecordReader initialized will read a total of 1 records.`
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - at row 0. reading next block`
`[main] INFO org.apache.parquet.hadoop.InternalParquetRecordReader - block read in memory in 1 ms. row count = 1`
`num_records=1`
`Retrieved 1 records`
`{"Message": "First record", "Number": d730d4db-da39-a943-a674-074f2ce33211`}

`{}Process finished with exit code 0{`}`{}{`}

I'll see about uploading my test program to github so you can try it.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17527519) / @theosib-amazon:
I've been trying to reproduce this with parquet-cli, but that tool is majorly broken. I'm filing PARQUET-2142 and PARQUET-2143 on this.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17527559) / @theosib-amazon:
I just realized that I managed to duplicate this in PARQUET-2143, so PARQUET-2143 should probably be resolved as a duplicate of this one. Now, if I can just figure out how to run this is a debugger...

EDIT: This is interesting. The guid.parquet file isn't the only one I have that parquet-cli can't parse. I also can't parse either of the files attached to PARQUET-2069. Both of those throw this error:
```

Unknown error
java.lang.RuntimeException: Failed on record 0
    at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:86)
    at org.apache.parquet.cli.Main.run(Main.java:157)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
    at org.apache.parquet.cli.Main.main(Main.java:187)
Caused by: java.lang.ClassCastException: optional binary element (STRING) is not a group
...
```

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17527592) / @theosib-amazon:
The error is caused in org.apache.parquet.io.ColumnIOFactory.visit(), where it sees that FIXED_LEN_BYTE_ARRAY in the file is not compatible with STRING, which is the type that it wants. It might be that if strictTypeChecking were off, this would work, but I haven't figured out how to disable it yet. If I force struct type checking off, it doesn't fail, but the results are kinds weird:
```

{"Message": "First record", "Number": "�0���9�C�t\u0007O,�2\u0011"}
```
I don't think this is the right way to handle this, though. Like why is it looking for a STRING in the first place? I can't find anything in the file that should indicate that this field ought to be interpreted as a string. It's always a FIXED_LEN_BYTE_ARRAY.

**Comment by asfimport** [comment]
[Balaji K](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17527712):
> I can't reproduce this bug with parquet-tools or 1.12.0 or 1.13.0-SNAPSHOT.

Based on this comment, it feels like a regression to me. Seems like older versions of the tool works and the newer versions could not?

@theosib-amazon if you could upload your test program to github and link me, that'd be kind of you. It will help me get started quicker as I'm very new to the Java ecosystem.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17528162) / @theosib-amazon:
I'm going to get back onto this today, so I'll probably upload my test code later today.

What's really strange is how inconsistent parquet-mr can be with regard to what it can read. If I write my own program to use the API or use parquet-tools from the command line, I can parse your file. If I use parquet-cli, there's a load of files I can't parse. It's almost as though parquet-mr has duplicate code in different places that's out of sync.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17528175) / @theosib-amazon:
Here's my minimal parquet reader that I've been using:

<https://github.com/theosib-amazon/parquet-mr-minreader>

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17528248) / @theosib-amazon:
I'm still working on this, but the problem appears to be in org.apache.parquet.avro.AvroSchemaConverter.convertField(). There's an anonymous inner class, where this method is defined:
```java

            @Override
            public Schema convertFIXED_LEN_BYTE_ARRAY(PrimitiveTypeName primitiveTypeName) {
              if (annotation instanceof LogicalTypeAnnotation.UUIDLogicalTypeAnnotation) {
                return Schema.create(Schema.Type.STRING);
              } else {
                int size = parquetType.asPrimitiveType().getTypeLength();
                return Schema.createFixed(parquetType.getName(), null, null, size);
              }
            }
```
The UUID from the file is indeed a UUIDLogicalTypeAnnotation, so this is specifying that the internal Avro schema to convert to should be STRING, which is elsewhere rejected as incompatible.

It looks like someone was attempting to add UUID support but didn't finish the job. If I edit this code so that it doesn't do that, then everything works. I don't get a UUID printed all pretty, but there's no exception. This is the output I get:
```

{"Message": "First record", "Number": [-41, 48, -44, -37, -38, 57, -87, 67, -90, 116, 7, 79, 44, -29, 50, 17]}
```
I have no idea how to fix this properly, since org.apache.parquet.io.ColumnIOFactory.visit() insists on strict type checking. So I'm going to create a PR to just make this not crash, in the hopes that someone who understands this better might provide some feedback.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17528263) / @theosib-amazon:
Never mind on that PR. It breaks other things. If instead of using parquet-cli I use my own Java code (<https://github.com/theosib-amazon/parquet-mr-minreader>), what used to work now break with the following error:
```

Caused by: java.lang.UnsupportedOperationException: fromFixed is not supported for uuid
```
It seems that there are different parts of ParquetMR that duplicate functionality, but they're out of sync. When adding UUID support for reading files, the author finished the job for the API, but that left the CLI code in a broken state.

Figuring out how these two codebases are out of sync and resolving them is going to require a higher level perspective on this project than what I have right now.

**Comment by asfimport** [comment]
[Balaji K](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17528352):
Thank you for sharing the details and for the min repro, @theosib-amazon – much appreciated. One more question, if I may - you mention "The UUID from the file is indeed a UUIDLogicalTypeAnnotation" – would you know if this is correct? i.e., would parquet-mr encode guids with the same annotation? also, how did you notice this annotation being present - by stepping through code or does parquet-tools/cli show this information?

many thanks.

As for parquet-cli, I suppose we'll have to wait for someone with more knowledge on these two codebases to weigh in on how to fix this.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17528393) / @theosib-amazon:
I got this information from a combination of System.out.println and stepping through the code with a debugger.

For your UUID field, this code in AvroSchemaConverter.java was used:

            @Override
            public Schema convertFIXED_LEN_BYTE_ARRAY(PrimitiveTypeName primitiveTypeName) {
              if (annotation instanceof LogicalTypeAnnotation.UUIDLogicalTypeAnnotation) {
                return Schema.create(Schema.Type.STRING);
              } else {
                int size = parquetType.asPrimitiveType().getTypeLength();
                return Schema.createFixed(parquetType.getName(), null, null, size);
              }
            }

I put a breakpoint here, and the debugger stopped here, and I was able to check the top of the annotation.


﻿On 4/26/22, 2:36 PM, "Balaji K (Jira)" <jira@apache.org> wrote:

    CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you can confirm the sender and know the content is safe.



         [ https://issues.apache.org/jira/browse/PARQUET-2140?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel ]

    Balaji K mentioned you on PARQUET-2140
    ------------------------------

    Thank you for sharing the details and for the min repro, @theosib-amazon – much appreciated. One more question, if I may - you mention "The UUID from the file is indeed a UUIDLogicalTypeAnnotation" – would you know if this is correct? i.e., would parquet-mr encode guids with the same annotation? also, how did you notice this annotation being present - by stepping through code or does parquet-tools/cli show this information?

    many thanks.

    As for parquet-cli, I suppose we'll have to wait for someone with more knowledge on these two codebases to weigh in on how to fix this.

    >                 Key: PARQUET-2140

    >         View Online: https://issues.apache.org/jira/browse/PARQUET-2140
    >         Add Comment: https://issues.apache.org/jira/browse/PARQUET-2140#add-comment

    Hint: You can mention someone in an issue description or comment by typing  "@" in front of their username.




    –
    This message was sent by Atlassian Jira
    (v8.20.7#820007)

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2140?#comment-17540138) / @theosib-amazon:
There's a slight chance that <https://github.com/apache/parquet-mr/pull/957> could fix this. I'll have to try to remember to test that out later.
