### ISSUE TITLE
Parquet fails to parse schema contains '\r'

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1726]
Parquet fails to parse schema contains '\r' for windows operating system.
	at parquet.schema.MessageTypeParser.asRepetition(MessageTypeParser.java:203)
at parquet.schema.MessageTypeParser.addType(MessageTypeParser.java:101)
at parquet.schema.MessageTypeParser.addGroupTypeFields(MessageTypeParser.java:96)
at parquet.schema.MessageTypeParser.parse(MessageTypeParser.java:89)
at parquet.schema.MessageTypeParser.parseMessageType(MessageTypeParser.java:79)
at org.apache.spark.sql.parquet.ParquetTestData$.writeFile(ParquetTestData.scala:221)
at org.apache.spark.sql.parquet.ParquetQuerySuite.beforeAll(ParquetQuerySuite.scala:92)

**Reporter**: [Rekha Joshi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rekhajoshm)
#### Related issues:
- [Parquet fails to parse schema contains '\r'](https://issues.apache.org/jira/browse/SPARK-5192) (is required by)

<sub>**Note**: *This issue was originally created as [PARQUET-176](https://issues.apache.org/jira/browse/PARQUET-176). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Rekha Joshi](https://issues.apache.org/jira/browse/PARQUET-176?#comment-14302494):
https://github.com/apache/incubator-parquet-mr/pull/112

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-176?#comment-14302546) / @rdblue:
`[~rekhajoshm]`, where did the Schema come from that you're using? I think this is a good addition, but I think we don't run into this much because not may people actually write Parquet Schemas by hand. Mostly, they're built by translating from some other object model's schema. If that's what you're doing and Parquet creates Schemas with \r when running on a windows platform, then I think there are two bugs to fix, not just this one.
