### ISSUE TITLE
parquet writer runs into OOM during writing when calling DataFrame.saveAsParquetFile in Spark SQL

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1763]
In Spark SQL, there is a function `saveAsParquetFile` in `DataFrame` or `SchemaRDD`. That function calls method in parquet-mr, and sometimes it will fail due to the OOM error thrown by parquet-mr. We can see the exception stack trace  as follows:

```
WARN] [task-result-getter-3] 03-19 11:17:58,274 [TaskSetManager] - Lost task 0.2 in stage 137.0 (TID 309, hb1.avoscloud.com): java.lang.OutOfMemoryError: Java heap space
        at parquet.column.values.dictionary.IntList.initSlab(IntList.java:87)
        at parquet.column.values.dictionary.IntList.<init>(IntList.java:83)
        at parquet.column.values.dictionary.DictionaryValuesWriter.<init>(DictionaryValuesWriter.java:85)
        at parquet.column.values.dictionary.DictionaryValuesWriter$PlainIntegerDictionaryValuesWriter.<init>(DictionaryValuesWriter.java:549)
        at parquet.column.ParquetProperties.getValuesWriter(ParquetProperties.java:88)
        at parquet.column.impl.ColumnWriterImpl.<init>(ColumnWriterImpl.java:74)
        at parquet.column.impl.ColumnWriteStoreImpl.newMemColumn(ColumnWriteStoreImpl.java:68)
        at parquet.column.impl.ColumnWriteStoreImpl.getColumnWriter(ColumnWriteStoreImpl.java:56)
        at parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.<init>(MessageColumnIO.java:178)
        at parquet.io.MessageColumnIO.getRecordWriter(MessageColumnIO.java:369)
        at parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:108)
        at parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:94)
        at parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:64)
        at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:282)
        at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:252)
        at org.apache.spark.sql.parquet.InsertIntoParquetTable.org$apache$spark$sql$parquet$InsertIntoParquetTable$$writeShard$1(ParquetTableOperations.scala:304)
        at org.apache.spark.sql.parquet.InsertIntoParquetTable$$anonfun$saveAsHadoopFile$1.apply(ParquetTableOperations.scala:325)
        at org.apache.spark.sql.parquet.InsertIntoParquetTable$$anonfun$saveAsHadoopFile$1.apply(ParquetTableOperations.scala:325)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:56)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
```

By the way, there is another similar issue https://issues.apache.org/jira/browse/PARQUET-99. But the reporter has closed it and mark it as resolved.

**Reporter**: [Chaozhong Yang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=debugger87)

<sub>**Note**: *This issue was originally created as [PARQUET-222](https://issues.apache.org/jira/browse/PARQUET-222). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14369698) / @rdblue:
The problem is usually that Parquet buffers records in memory to write them as large groups; by default 128MB of space is required for each open file. I'm not sure how Spark SQL is writing data, but multiple open files can easily cause an OOM exception. What is the heap space allocated to your task?

**Comment by asfimport** [comment]
[Chaozhong Yang](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14370906):
@rdblue I set the heap size to 512m. But every row of records has thousands of columns, so it throw OOM exception.

**Comment by asfimport** [comment]
[Daniel Weeks](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14371548) / @danielcweeks:
`[~debugger87]` You're probably going to need a much larger heap than 512m.  There simply isn't enough headroom for the process and parquet to coexist.  We currently run with a 10GB heap for Spark.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14551354) / @rdblue:
`[~debugger87]` did you get past this problem? Can we close this issue?

**Comment by asfimport** [comment]
[madhukara phatak](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14574867):
I am getting same issue for a file with 26k columns but single row. Even after I have set 4gb heap space, I am getting OOM

**Comment by asfimport** [comment]
[Daniel Weeks](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14574880) / @danielcweeks:
I believe you are running into the problem described in PARQUET-183 due to the number of columns you have.

**Comment by asfimport** [comment]
[madhukara phatak](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14574886):
Is there is any stats on how many columns current format can handle? And also I don't have sparse columns, all columns have value. Is it too much for paquet?

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14574894) / @rdblue:
[~phatak.dev]: the problem is probably the number of files you're trying to write to at once. Each file buffers to the Parquet row group size (set by parquet.block.size, defaults to 128MB). If you have 10 files open for a processor, that's ~1.3GB and Spark already uses quite a bit of memory itself.

[~lian cheng], any ideas since you're the most familiar with how Spark writes from data frames? Is it possible to shuffle the data to have only one open file per executor at a time?

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14575783) / @liancheng:
There are several ways to alleviate this.

Firstly, for those DataFrames whose data sizes are small (e.g., the single row case [~phatak.dev] mentioned), you may try `df.coalesce(1)` to reduce partition number to 1.  In this way, only a single file will be written.  In most cases, the default parallelism equals to the number of cores.  For example, if you are running a Spark application with a single executor on a single 8-core node, that executor process needs to write 8 Parquet files even there's only a single row.

Secondly, when you are writing DataFrames with large volume, you may try to adjust DataFrame partition number (via `df.repartition(m)` and/or `df.coalesce(m)`) and executor number (via the `--num-executors` flag of `spark-submit`) to ensure the former is less than or equal to the latter, so that each executor process only opens and writes one Parquet file on average.

And of course, heap size of a single executor should be large enough to allow Parquet to write at least a single file.

**Comment by asfimport** [comment]
[madhukara phatak](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14576292):
It doesn't seems to be partitions issues.  I am running in local, with master set as "local". I also printed number of partitions reported by df.rdd.partitions.length. It is equal to 1.

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14577257) / @liancheng:
Hey [~phatak.dev], thanks for the information.  I tried to reproduce this issue with the following Spark shell snippet:
```Java
import sqlContext._
import sqlContext.implicits._

import org.apache.spark.sql.types._
import org.apache.spark.sql.Row

val n = 26000
val schema = StructType((1 to n).map(i => StructField(s"f$i", IntegerType, nullable = false)))
val bigRow = Row((1 to n): _*)
val df = createDataFrame(sc.parallelize(bigRow :: Nil), schema)
df.coalesce(1).write.mode("overwrite").format("orc").save("file:///tmp/foo")
```
I was using Spark 1.4.0-SNAPSHOT.  Command line used to start the shell is:
```
./bin/spark-shell --driver-memory 4g
```
I didn't get an OOM, but it does hang like forever.  After profiling it with YJP, it turns out that this super wide table is somehow stressing out the query planner by making Spark SQL allocates a large number of small objects.  Haven't tried 1.3.1 yet. Will do when I got time.

I found that you had once posted this issue to Spark user mailing list.  Would you mind to provide a full stack trace of the OOM error?  Maybe it's more like a Spark SQL issue rather than a Parquet issue.

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14577258) / @liancheng:
Specifically, I think your problem is different from the one described in this JIRA ticket.

**Comment by asfimport** [comment]
[madhukara phatak](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14577276):
The following is the complete stack trace

```Java
java.lang.OutOfMemoryError: Java heap space
	at parquet.column.values.dictionary.IntList.initSlab(IntList.java:87)
	at parquet.column.values.dictionary.IntList.<init>(IntList.java:83)
	at parquet.column.values.dictionary.DictionaryValuesWriter.<init>(DictionaryValuesWriter.java:85)
	at parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter.<init>(DictionaryValuesWriter.java:251)
	at parquet.column.ParquetProperties.getValuesWriter(ParquetProperties.java:77)
	at parquet.column.impl.ColumnWriterImpl.<init>(ColumnWriterImpl.java:74)
	at parquet.column.impl.ColumnWriteStoreImpl.newMemColumn(ColumnWriteStoreImpl.java:68)
	at parquet.column.impl.ColumnWriteStoreImpl.getColumnWriter(ColumnWriteStoreImpl.java:56)
	at parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.<init>(MessageColumnIO.java:178)
	at parquet.io.MessageColumnIO.getRecordWriter(MessageColumnIO.java:369)
	at parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:108)
	at parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:94)
	at parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:64)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:282)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:252)
	at org.apache.spark.sql.parquet.ParquetRelation2.org$apache$spark$sql$parquet$ParquetRelation2$$writeShard$1(newParquet.scala:667)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
15/06/08 20:11:07 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-1,5,main]
java.lang.OutOfMemoryError: Java heap space
	at parquet.column.values.dictionary.IntList.initSlab(IntList.java:87)
	at parquet.column.values.dictionary.IntList.<init>(IntList.java:83)
	at parquet.column.values.dictionary.DictionaryValuesWriter.<init>(DictionaryValuesWriter.java:85)
	at parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter.<init>(DictionaryValuesWriter.java:251)
	at parquet.column.ParquetProperties.getValuesWriter(ParquetProperties.java:77)
	at parquet.column.impl.ColumnWriterImpl.<init>(ColumnWriterImpl.java:74)
	at parquet.column.impl.ColumnWriteStoreImpl.newMemColumn(ColumnWriteStoreImpl.java:68)
	at parquet.column.impl.ColumnWriteStoreImpl.getColumnWriter(ColumnWriteStoreImpl.java:56)
	at parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.<init>(MessageColumnIO.java:178)
	at parquet.io.MessageColumnIO.getRecordWriter(MessageColumnIO.java:369)
	at parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:108)
	at parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:94)
	at parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:64)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:282)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:252)
	at org.apache.spark.sql.parquet.ParquetRelation2.org$apache$spark$sql$parquet$ParquetRelation2$$writeShard$1(newParquet.scala:667)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
15/06/08 20:11:07 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1, localhost): java.lang.OutOfMemoryError: Java heap space
	at parquet.column.values.dictionary.IntList.initSlab(IntList.java:87)
	at parquet.column.values.dictionary.IntList.<init>(IntList.java:83)
	at parquet.column.values.dictionary.DictionaryValuesWriter.<init>(DictionaryValuesWriter.java:85)
	at parquet.column.values.dictionary.DictionaryValuesWriter$PlainBinaryDictionaryValuesWriter.<init>(DictionaryValuesWriter.java:251)
	at parquet.column.ParquetProperties.getValuesWriter(ParquetProperties.java:77)
	at parquet.column.impl.ColumnWriterImpl.<init>(ColumnWriterImpl.java:74)
	at parquet.column.impl.ColumnWriteStoreImpl.newMemColumn(ColumnWriteStoreImpl.java:68)
	at parquet.column.impl.ColumnWriteStoreImpl.getColumnWriter(ColumnWriteStoreImpl.java:56)
	at parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.<init>(MessageColumnIO.java:178)
	at parquet.io.MessageColumnIO.getRecordWriter(MessageColumnIO.java:369)
	at parquet.hadoop.InternalParquetRecordWriter.initStore(InternalParquetRecordWriter.java:108)
	at parquet.hadoop.InternalParquetRecordWriter.<init>(InternalParquetRecordWriter.java:94)
	at parquet.hadoop.ParquetRecordWriter.<init>(ParquetRecordWriter.java:64)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:282)
	at parquet.hadoop.ParquetOutputFormat.getRecordWriter(ParquetOutputFormat.java:252)
	at org.apache.spark.sql.parquet.ParquetRelation2.org$apache$spark$sql$parquet$ParquetRelation2$$writeShard$1(newParquet.scala:667)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14577304) / @liancheng:
Thanks! I'll try 1.3.1 later.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14577423) / @rdblue:
[~lian cheng], in other frameworks, we've gotten around this issue by re-partitioning the data using the final partition keys that will be used on disk. That way, each task needs just one file open and a long-running executor is much less likely to hit this problem because memory consumption grows per file. Does Spark have anything like that? You mentioned repartition above, but I didn't get the impression that it would ensure the fewest number of files. Sounds like that just spreads the work between more tasks.

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14580339) / @liancheng:
Hey [~phatak.dev], finally got some time to try 1.3.1 and reproduced this OOM.

While trying this case with 1.4, it got stuck in the query planner, so I was adjusting `\-\-driver-memory`.  In the case of 1.3.1, by tuning `\-\-executor-memory`, I can see two kinds of exceptions.  The first one is exactly the same as what you saw.  In my test code, I create 26k INT columns, so Parquet tries to initialize 26k column writers, each allocates a default slab (an `int[]`) with 64k elements.  This takes at least `26k * 64k * 4b = 6.34gb` memory.

After increasing executor memory to 10g, I saw similar exception thrown from `RunLengthBitPackingHybridEncoder`.  I guess Parquet is trying to allocate an RLE encoder for each column here to perform compression (not 100% sure about this for now).  Similarly, each encoder initializes a default slab (a `byte[]`) with at least 64k elements, and that's another `26k * 64k * 1b = 1.6gb` memory.

Only have a laptop for now, so... not sure how much memory it needs to write such wide a table.  But essentially Parquet needs to pre-allocate some memory for each column to compress and buffer data.  And 26k columns altogether just eats too much memory here.  That's why even your table has only a single row, it still causes OOM.

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14580765) / @liancheng:
Hey @rdblue, it seems that you are referring to use cases like writing to Hive dynamic partitions (where a single task may need to write to write multiple Parquet files according to partition column values)?  I believe the use case described in the JIRA description is different.  Unlike Hive or Pig, which use process level parallelism, Spark uses thread level parallelism (tasks are executed in thread pool).  And currently, there's no way to "pin" a Spark task to a specific process.  So even each task is guaranteed to write at most one Parquet file, it's still possible for a single executor process to write multiple Parquet files at some point.  So in the scope of Spark, currently there isn't a very good mechanism to fix this problem.  What I suggested was essentially to shrink partition number so that on average an executor writes only a single file (I made a mistake in my previous comment and said "at most one Parquet file", it should be "on average").

In case of dynamic partitioning, we do plan to re-partition the data according to partition column values before writing the data to reduce number of parallel writers.  Another possible approach was to sort the data within each task before writing, so that only a single writer is active for a task at any point of time.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14580861) / @rdblue:
Okay, so it sounds like you're talking about writing out data to a single folder without FS partitioning. Then, I agree that the solution to reduce the number of tasks so to try and minimize the number of files. Sounds like you already do the optimization for FS partitioning, which is great. Thanks!

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14583626) / @rdblue:
It doesn't sound like there are any bugs here, just that Parquet + Spark takes a lot of memory, right? Anyone opposed to closing this?

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14583691) / @liancheng:
I tend to agree this issue can be closed.

The problem is that if two or more tasks that are writing Parquet files are happened to be scheduled to a single Spark executor, and the Parquet file happened to have relatively more fields, then it tends to OOM.  Reducing partition numbers via `DataFrame.repartition()` before writing Parquet files can be a reasonable workaround for this issue.  But I don't see a good workaround for super wide tables (e.g., the 26k columns case discussed above) yet.  Maybe we can have a separate JIRA for writing wide sparse Parquet tables.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14583703) / @rdblue:
I'm closing because this isn't something we can directly fix. Thanks to [~lian cheng] for providing information to avoid the problem, I think that's the best solution right now.

**Comment by asfimport** [comment]
[Daniel Weeks](https://issues.apache.org/jira/browse/PARQUET-222?#comment-14583752) / @danielcweeks:
[~lian cheng]  For extremely wide tables like this, columnar may not work particularly well for a number of reasons.  Beyond just the memory issues, you'll only get a few rows per page/row group which will result in poor compression and degraded performance on the read side as well.  There are other ways to improve performance for extremely wide tables, but most columnar format won't be optimal.
