### ISSUE TITLE
NPE in ParquetInputFormat.getSplits when no .parquet files exist

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1821]
```Java
        JavaSparkContext context = ...
        JavaRDD<Row> rdd1 = context.parallelize(ImmutableList.<Row> of());
        SQLContext sqlContext = new SQLContext(context);
        StructType schema = DataTypes.createStructType(ImmutableList.of(DataTypes.createStructField("col1", DataTypes.StringType, true)));
        DataFrame df = sqlContext.createDataFrame(rdd1, schema);
        String url = "file:///tmp/emptyRDD";
        df.saveAsParquetFile(url);

        Configuration configuration = SparkHadoopUtil.get().newConfiguration(context.getConf());
        JobConf jobConf = new JobConf(configuration);
        ParquetInputFormat.setReadSupportClass(jobConf, RowReadSupport.class);
        FileInputFormat.setInputPaths(jobConf, url);
        JavaRDD<Row> rdd2 = context.newAPIHadoopRDD(
            jobConf, ParquetInputFormat.class, Void.class, Row.class).values();
        rdd2.count();

        df = sqlContext.createDataFrame(rdd2, schema);
        url = "file:///tmp/emptyRDD2";
        df.saveAsParquetFile(url);

        FileInputFormat.setInputPaths(jobConf, url);
        JavaRDD<Row> rdd3 = context.newAPIHadoopRDD(
            jobConf, ParquetInputFormat.class, Void.class, Row.class).values();
        rdd3.count();
```

The NPE happens here:
```Java
java.lang.NullPointerException
	at parquet.hadoop.ParquetInputFormat.getSplits(ParquetInputFormat.java:263)
	at parquet.hadoop.ParquetInputFormat.getSplits(ParquetInputFormat.java:245)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:95)
```

This stems from ParquetFileWriter.getGlobalMetaData returning null when there are no footers to read.

**Reporter**: [Paul Nepywoda](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pnepywoda)

<sub>**Note**: *This issue was originally created as [PARQUET-294](https://issues.apache.org/jira/browse/PARQUET-294). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Paul Nepywoda](https://issues.apache.org/jira/browse/PARQUET-294?#comment-14565457):
Running on parquet-hadoop-1.6.0rc3 which is what Spark 1.3.1 depends on.

**Comment by asfimport** [comment]
[Cheng Lian](https://issues.apache.org/jira/browse/PARQUET-294?#comment-14576258) / @liancheng:
Is this related to PARQUET-151?
