### ISSUE TITLE
parquet-cat json dump is broken for maps

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1876]
When dumping parquet maps as json with the parquet-cat tool it throws class cast exception.

```
parquet-cat --debug --json file:///tmp/test.parquet

java.lang.ClassCastException: [B cannot be cast to java.lang.String
	at org.apache.parquet.tools.read.SimpleMapRecord.toJsonObject(SimpleMapRecord.java:34)
	at org.apache.parquet.tools.read.SimpleRecord.toJsonValue(SimpleRecord.java:119)
	at org.apache.parquet.tools.read.SimpleRecord.toJsonObject(SimpleRecord.java:112)
	at org.apache.parquet.tools.read.SimpleRecord.prettyPrintJson(SimpleRecord.java:106)
	at org.apache.parquet.tools.command.CatCommand.execute(CatCommand.java:76)
	at org.apache.parquet.tools.Main.main(Main.java:222)
[B cannot be cast to java.lang.String
```

**Reporter**: [Nezih Yigitbasi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nezihyigitbasi) / @nezihyigitbasi
**Assignee**: [Nezih Yigitbasi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nezihyigitbasi) / @nezihyigitbasi
#### PRs and other links:
- [PR-259](https://github.com/apache/parquet-mr/pull/259)

<sub>**Note**: *This issue was originally created as [PARQUET-360](https://issues.apache.org/jira/browse/PARQUET-360). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-360?#comment-14803410) / @rdblue:
Merged #360. Thanks @nezihyigitbasi!
