### ISSUE TITLE
Cascading and scrooge builds fail when using thrift 0.9.0

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1892]
This is caused by a transitive dependency on libthrift 0.7.0 from elephantbird. The solution is to add thrift as an explicit (but provided) dependency to those projects.

**Reporter**: [Ryan Blue](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rdblue) / @rdblue
**Assignee**: [Ryan Blue](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rdblue) / @rdblue
#### Related issues:
- [Parquet build fails with thrift9 profile ](https://issues.apache.org/jira/browse/PARQUET-391) (is duplicated by)
#### PRs and other links:
- [PR #276](https://github.com/apache/parquet-mr/pull/276)

<sub>**Note**: *This issue was originally created as [PARQUET-380](https://issues.apache.org/jira/browse/PARQUET-380). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Yash Datta](https://issues.apache.org/jira/browse/PARQUET-380?#comment-15008461) / @saucam:
Any updates ?

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-380?#comment-15009063) / @rdblue:
There are build failures from thrift's SLF4J dependency. I just need to have some time to work through it.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-380?#comment-15009838) / @rdblue:
When I add the dependency for libthrift, I get an error somewhere in cascading that there is no StaticLoggerBinder for SLF4J. That's an easy fix: add a binder like slf4j-nop or slf4j-simple. But, when I add slf4j-simple:1.7.5, I get:

```Java
SLF4J: The requested version 1.6.99 by your slf4j binding is not compatible with [1.5.5, 1.5.6, 1.5.7, 1.5.8]
. . .
java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.format(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
  at org.slf4j.impl.SimpleLogger.formatAndLog(SimpleLogger.java:414)
  at org.slf4j.impl.SimpleLogger.info(SimpleLogger.java:546)
```

The version of SLF4J that is pulled in by libthrift is too old to work with a new binding. But, using a slf4j-simple version that works with the older version of thrift causes failures in the hadoop-2 profile because Hadoop pulls in a version of SLF4J that isn't compatible with the older slf4j-simple. So the fix is to pull in the new version of both slf4j-api and slf4j-simple that matches the hadoop-2 verison. In the default profile, it overrides the transitive SLF4J dependency from libthrift and everything works. This is only needed for test dependencies, allowing downstream projects to use whatever version of the SLF4J API they need, which will override the old one in libthrift.

I've pushed a new version that should work, I'll commit it after CI tests pass.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-380?#comment-15009872) / @rdblue:
Fixed. Thanks for the push, @saucam!

**Comment by asfimport** [comment]
[Yash Datta](https://issues.apache.org/jira/browse/PARQUET-380?#comment-15010337) / @saucam:
Thanks for fixing this @rdblue ! I was kind of blocked on this :)
