### ISSUE TITLE
Backwards-incompatible change to thrift metadata

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1914]
Sometime in the last few versions, a `isStructOrUnion` field has been added to the `thrift.descriptor` written to the parquet header:

```Java
{
    "children": [ ... ],
    "id": "STRUCT", 
    "structOrUnionType": "STRUCT"
}
```

The current release now throws an exception when that field is missing  / `UNKNOWN`). This makes it impossible to read back thrift data written using a previous release.

**Reporter**: [Ben Kirwin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bkirwi)
#### Related issues:
- [ThriftSchemaConverter throws for unknown struct or union type](https://issues.apache.org/jira/browse/PARQUET-346) (duplicates)

<sub>**Note**: *This issue was originally created as [PARQUET-405](https://issues.apache.org/jira/browse/PARQUET-405). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Ben Kirwin](https://issues.apache.org/jira/browse/PARQUET-405?#comment-15056802):
Failure stacktrace:

```Java
Caused by: org.apache.parquet.ShouldNeverHappenException: Encountered UNKNOWN StructOrUnionType
    at org.apache.parquet.thrift.ThriftSchemaConvertVisitor.isUnion(ThriftSchemaConvertVisitor.java:337)
    at org.apache.parquet.thrift.ThriftSchemaConvertVisitor.visit(ThriftSchemaConvertVisitor.java:213)
    at org.apache.parquet.thrift.ThriftSchemaConvertVisitor.visit(ThriftSchemaConvertVisitor.java:76)
    at org.apache.parquet.thrift.struct.ThriftType$StructType.accept(ThriftType.java:272)
    at org.apache.parquet.thrift.ThriftSchemaConvertVisitor.convert(ThriftSchemaConvertVisitor.java:88)
    at org.apache.parquet.thrift.ThriftSchemaConverter.convert(ThriftSchemaConverter.java:60)
    at org.apache.parquet.thrift.ThriftRecordConverter.<init>(ThriftRecordConverter.java:797)
    at org.apache.parquet.scrooge.ScroogeRecordConverter.<init>(ScroogeRecordConverter.java:36)
```

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-405?#comment-15057013) / @rdblue:
Thanks, Ben! Both for reporting the issue and for helping us keep the issues organized.
