### ISSUE TITLE
Shutdown hook in parquet-avro library corrupts data and disables logging

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1916]
Parquet-avro and probably also other Parquet libraries are not well behaved. It registers a shutdown hook that bypasses application shutdown sequence, corrupts data written to currently opened Parquet file(s) and disables or reconfigures slf4j/logback logger so no further log message is visible.

### Scope

Our application is a microservice that handles stop request in form of signal SIGTERM, resp. JVM shutdown hook. If it arrives the application will close all opened files (writers), release all other resources and gracefully shutdown. We are swiching from sequence files to Parquet at the moment and using Maven dependency `org.apache.parquet:parquet-avro:1.8.1` which is current latest version. We are using `Runtime.getRuntime().addShutdownHook()` to handle SIGTERM.

### Example code

See archive in attachment.

- Optionally update version of `hadoop-client` in `pom.xml` to match your Hadoop.
- Use `mvn package` to compile.
- Copy Hadoop configuration XMLs to `config` directory.
- Update configuration at the top of `ParquetBrokenShutdown` class.
- Execute `ParquetBrokenShutdown` class.
- Send SIGTERM to shutdown the application (`kill PID`).

### Initial analysis

Parquet library tries to care about application shutdown but this introduces more issues than solves. If application is writing to a file and the library asynchronously decides to close underlying writer, data loss will occur. The handle is just closed and all remaining records can't be written.

```
Writing to HDFS/Parquet failed
java.io.IOException: can not write PageHeader(type:DICTIONARY_PAGE, uncompressed_page_size:14, compressed_page_size:34, dictionary_page_header:DictionaryPageHeader(num_values:1, encoding:PLAIN))
	at org.apache.parquet.format.Util.write(Util.java:224)
	at org.apache.parquet.format.Util.writePageHeader(Util.java:61)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.writeDictionaryPageHeader(ParquetMetadataConverter.java:760)
	at org.apache.parquet.hadoop.ParquetFileWriter.writeDictionaryPage(ParquetFileWriter.java:307)
	at org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writeToFileWriter(ColumnChunkPageWriteStore.java:179)
	at org.apache.parquet.hadoop.ColumnChunkPageWriteStore.flushToFileWriter(ColumnChunkPageWriteStore.java:238)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:165)
	at org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:113)
	at org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:297)
	at com.avast.bugreport.parquet.ParquetBrokenShutdown.writeParquetFile(ParquetBrokenShutdown.java:86)
	at com.avast.bugreport.parquet.ParquetBrokenShutdown.run(ParquetBrokenShutdown.java:53)
	at com.avast.bugreport.parquet.ParquetBrokenShutdown.main(ParquetBrokenShutdown.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: parquet.org.apache.thrift.transport.TTransportException: java.nio.channels.ClosedChannelException
	at parquet.org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:147)
	at parquet.org.apache.thrift.transport.TTransport.write(TTransport.java:105)
	at parquet.org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:424)
	at parquet.org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:431)
	at parquet.org.apache.thrift.protocol.TCompactProtocol.writeFieldBeginInternal(TCompactProtocol.java:194)
	at parquet.org.apache.thrift.protocol.TCompactProtocol.writeFieldBegin(TCompactProtocol.java:176)
	at org.apache.parquet.format.InterningProtocol.writeFieldBegin(InterningProtocol.java:74)
	at org.apache.parquet.format.PageHeader.write(PageHeader.java:918)
	at org.apache.parquet.format.Util.write(Util.java:222)
	... 16 more
Caused by: java.nio.channels.ClosedChannelException
	at org.apache.hadoop.hdfs.DFSOutputStream.checkClosed(DFSOutputStream.java:1635)
	at org.apache.hadoop.fs.FSOutputSummer.write(FSOutputSummer.java:104)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:58)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at parquet.org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:145)
	... 24 more
```

Stored file is also currupted in such case. It contains only four bytes "PAR1" header so actually all data are lost.

Together with that whole application logging using slf4j/logback is reconfigured or completely disabled so no more application's log messages appear in the output. This may be related to PARQUET-369 and will be hopefully fixed in PARQUET-401. No such issue was observed when sequence files were used in the past.

### Known workaround

Java executes threads of shutdown hooks independently and in parallel, but it is possible for the application to force its own shutdown to be executed before the Parquet's one. Parquet library uses Hadoop's `ShutdownHookManager` to register the hook which has a possibility to define a priority.

```
if (!USE_WORKAROUND) {
	Runtime.getRuntime().addShutdownHook(shutdownHook);
} else {
	int maxPriority = Integer.MAX_VALUE; // Execute application hook before hook in Hadoop library
	ShutdownHookManager.get().addShutdownHook(shutdownHook, maxPriority);
}
```

This workaround would be impossible if there are two or more such nasty libraries.

No workaround has been found for the second issue with disabled logging until now.

### Suggestions for fix

- Never touch logging configuration in libraries.
  - Use slf4j-api interfaces and just output log messages.
  - Application is responsible for configuration of logging.
- Do not register any shutdown hook in libraries that releases resources that are still possibly in use.
  - Instead provide an API to the application to close/free the allocated resources (already present).
  - The application is responsible to call close on all Closeables during shutdown in correct order and correct time.
  - No library has enough information for that.
- Be well behaved library, do not try to be smarter than the application, it isn't possible.

**Reporter**: [Michal Turek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=turek@avast.com) / @mixalturek
**Assignee**: [Michal Turek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=turek@avast.com) / @mixalturek
#### Related issues:
- [Shading SLF4J prevents SLF4J locating org.slf4j.impl.StaticLoggerBinder](https://issues.apache.org/jira/browse/PARQUET-369) (is related to)
- [Deprecate Log and move to SLF4J Logger](https://issues.apache.org/jira/browse/PARQUET-401) (requires)
- [Format: Do not shade slf4j-api](https://issues.apache.org/jira/browse/PARQUET-412) (requires)
#### Original Issue Attachments:
- [parquet-broken-shutdown_2015-12-16.tar.gz](https://issues.apache.org/jira/secure/attachment/12777996/parquet-broken-shutdown_2015-12-16.tar.gz)

<sub>**Note**: *This issue was originally created as [PARQUET-408](https://issues.apache.org/jira/browse/PARQUET-408). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15060737) / @rdblue:
[~turek@avast.com], thank you for the very detailed report of what you're seeing. Bug reports like this are much easier to work with.

I'm not sure I'm convinced that this is a bug with Parquet. If I understand correctly, you're using a Java 7 try-with-resources block to instantiate the parquet-avro writer, which is calls close on that writer when it exits. That happens only when the thread is signaled via AtomicBoolean finished. Finished is set in your shutdown hook, so your when hook runs, it gracefully shuts down the writing thread, which closes the file. But the error you're seeing is from closing the Parquet file after the underlying file stream has been closed. Parquet doesn't have a shutdown hook that causes that, I think [HDFS does](https://github.com/apache/hadoop/blob/cbc7b6bf97a80c39d4bbb3005e42dacae6726baf/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L2873).

I think the problem is that your hook gets called to shut down after the HDFS client closes all of its connections. That's solved by your work-around, which I think isn't a work around so much as the only way to do what you want to with HDFS. :)

Does that sound reasonable? I think the logging issues are unrelated, too.

**Comment by asfimport** [comment]
[Michal Turek](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15061970) / @mixalturek:
Hi Ryan, thank you for the very quick response and pointing to FileSystem class. I found configuration "fs.automatic.close" in its code, setting it to "false" solves the corruption of files too.

https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/core-default.xml

> By default, FileSystem instances are automatically closed at program exit using a JVM shutdown hook. Setting this property to false disables this behavior. This is an advanced option that should only be used by server applications requiring a more carefully orchestrated shutdown sequence.

I don't expect that the last closed Parquet writer will also close the underlying instance of FileSystem, on the other hand it is not accessible to the application code at all. Should I call static `FileSystem.closeAll()` by myself? It's pretty undocumented and looks like broken by design in Hadoop... or I missed something again.

Why do you think the logging issues are unrelated? Parquet library disables application logging for no reason, it looks like very related for me. I have updated the example to support also sequence files to show you differences (parquet-broken-shutdown_2015-12-17.tar.gz). 

While using sequence files I see:

```
...
2015-12-17 13:09:30.249 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:136)
2015-12-17 13:09:31.250 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:136)
Logging test: stopping application
2015-12-17 13:09:31.913 INFO  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: =============== STOPPING APPLICATION =============== (ParquetBrokenShutdown.java:176)
2015-12-17 13:09:31.913 TRACE c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: stopping application (ParquetBrokenShutdown.java:177)
2015-12-17 13:09:31.913 DEBUG c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: stopping application (ParquetBrokenShutdown.java:178)
2015-12-17 13:09:31.913 INFO  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: stopping application (ParquetBrokenShutdown.java:179)
2015-12-17 13:09:31.913 WARN  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: stopping application (ParquetBrokenShutdown.java:180)
2015-12-17 13:09:31.913 ERROR c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: stopping application (ParquetBrokenShutdown.java:181)
2015-12-17 13:09:31.913 INFO  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Closing instance (ParquetBrokenShutdown.java:61)
2015-12-17 13:09:32.251 DEBUG c.a.b.parquet.ParquetBrokenShutdown [main]: Closing sequence file: hdfs://nameservice1/user/turek/bugreport.seq (ParquetBrokenShutdown.java:141)
2015-12-17 13:09:32.425 DEBUG c.a.b.parquet.ParquetBrokenShutdown [main]: Sequence file closed: hdfs://nameservice1/user/turek/bugreport.seq (ParquetBrokenShutdown.java:144)
2015-12-17 13:09:32.425 INFO  c.a.b.parquet.ParquetBrokenShutdown [main]: =============== APPLICATION FINISHED =============== (ParquetBrokenShutdown.java:176)
2015-12-17 13:09:32.425 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application finished (ParquetBrokenShutdown.java:177)
2015-12-17 13:09:32.426 DEBUG c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application finished (ParquetBrokenShutdown.java:178)
2015-12-17 13:09:32.426 INFO  c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application finished (ParquetBrokenShutdown.java:179)
2015-12-17 13:09:32.426 WARN  c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application finished (ParquetBrokenShutdown.java:180)
2015-12-17 13:09:32.426 ERROR c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application finished (ParquetBrokenShutdown.java:181)
Logging test: application finished
2015-12-17 13:09:32.527 INFO  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: =============== SHUTDOWN HOOK FINISHED =============== (ParquetBrokenShutdown.java:176)
2015-12-17 13:09:32.528 TRACE c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: shutdown hook finished (ParquetBrokenShutdown.java:177)
2015-12-17 13:09:32.528 DEBUG c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: shutdown hook finished (ParquetBrokenShutdown.java:178)
2015-12-17 13:09:32.528 INFO  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: shutdown hook finished (ParquetBrokenShutdown.java:179)
2015-12-17 13:09:32.528 WARN  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: shutdown hook finished (ParquetBrokenShutdown.java:180)
2015-12-17 13:09:32.528 ERROR c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: Logging test: shutdown hook finished (ParquetBrokenShutdown.java:181)
Logging test: shutdown hook finished
```

But while using Parquet files and parquet-avro library I see only:

```
...
2015-12-17 13:10:36.909 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:110)
2015-12-17 13:10:37.910 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:110)
Logging test: stopping application
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Logging test: application finished
Logging test: shutdown hook finished
```

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15062411) / @rdblue:
After you're done closing Parquet files, I think you should call `FileSystem.closeAll()` since that is what the hook you've disabled would do.

I think your file corruption issue is now understood and the logging problem isn't causing it. That's what I mean when I say they are independent.

PARQUET-369 will only drop logs from thrift within parquet-format, and the only one I've seen is when close, not flush, fails. That didn't happen here because the exception wasn't caught, logged, and suppressed in thrift. It was correctly propagated up to your application. You can see in the stack trace that it went through TIOStreamTransport. You may be right that we should expose the logs with the trade-off of adding the dependency, which we are discussing on that issue.

I'm not sure what the problem you're seeing in this application is, but it looks like it is related to not configuring SLF4J. All of the log lines you list above that are missing are from your application, not from calls into Parquet.

**Comment by asfimport** [comment]
[Jim Gawron](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15144967):
Logging breaks in shutdown hooks because log4js own shutdown hook is being called in parallel with the others. This can be disabled via configuration in log4j2.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15147589) / @rdblue:
Thanks, Jim! I think that closes out what we needed to explain here. We'll follow up on the Parquet logging changes in PARQUET-412 and I'll close this issue. Feel free to re-open if I missed something.

**Comment by asfimport** [comment]
[Michal Turek](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15148233) / @mixalturek:
Hi Jim, can you point to a related code snippet where log4j2 comes from? I can't find anything, where did you find it? Is it shadowed somewhere similarly to slf4j-api and slf4j-nop in parquet-format? Our project doesn't use it at all and there is no related JAR in dependencies. We use standard slf4j-api, various slf4j bridges and logback as logger implementation. It's also quite bad idea to configure logging of everything e.g. in logback.xml and have a second configuration file only due to one concrete library that is not well behaved. Am I the only one who see it? ;-)

```
find . -name '*log4j*'
./log4j-over-slf4j-1.7.14.jar
```

**Comment by asfimport** [comment]
[Michal Turek](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15148323) / @mixalturek:
I have just tried to add `log4j.xml` and `log4j2.xml` on classpath but it didn't help as expected.

http://coders-kitchen.com/2014/01/29/tip-disable-log4j-2s-shutdown-handler/

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" monitoringInterval="30" shutdownHook="disable">
    <!-- Empty -->
</Configuration>
```

Adding `import org.apache.logging.log4j.Logger;` introduces a compiler error so I'm pretty sure, log4j2 is not the cause.

Can you update the attached sample code and make it functional to demonstrate your fix, please?

**Comment by asfimport** [comment]
[Michal Turek](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15148540) / @mixalturek:
Ok, I was debugging for a while and finally found what is happening. Logging is not disabled on shutdown at all but shutdown hook of `java.util.logging` corrupts stdout stream. Messages that go to `System.out` using `ConsoleAppender` are not written, because the stream is closed. On the other hand messages that go to a file using `RollingFileAppender` are correctly there.

Bellow is a detailed analysis if anyone is interested. Note there is a workaround at the very end.


Effective logback.xml:

```
<?xml version="1.0" encoding="UTF-8" ?>
<configuration scan="true" scanPeriod="30 seconds">
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-35logger{35} [%thread]: %msg \(%file:%line\)%n%xThrowable{full}</pattern>
        </encoder>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>test.log</file>

        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>test.log.%d{yyyy-MM-dd}_%i.gz</fileNamePattern>
            <maxHistory>30</maxHistory>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>250MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
        </rollingPolicy>

        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-45logger{45} [%thread]: %msg%n%xThrowable{full}</pattern>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="FILE"/>
    </root>

    <logger name="com.avast.bugreport" level="TRACE"/>
</configuration>
```


Output on console or in JIdea IDE:

```
Logging test: starting application
Logging test: application started
2016-02-16 12:39:58.922 INFO  c.a.b.parquet.ParquetBrokenShutdown [main]: =============== STARTING APPLICATION =============== (ParquetBrokenShutdown.java:177)
2016-02-16 12:39:58.928 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: starting application (ParquetBrokenShutdown.java:178)
2016-02-16 12:39:58.928 DEBUG c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: starting application (ParquetBrokenShutdown.java:179)
2016-02-16 12:39:58.928 INFO  c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: starting application (ParquetBrokenShutdown.java:180)
2016-02-16 12:39:58.928 WARN  c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: starting application (ParquetBrokenShutdown.java:181)
2016-02-16 12:39:58.928 ERROR c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: starting application (ParquetBrokenShutdown.java:182)
2016-02-16 12:39:58.929 INFO  c.a.b.parquet.ParquetBrokenShutdown [main]: =============== APPLICATION STARTED =============== (ParquetBrokenShutdown.java:177)
2016-02-16 12:39:58.930 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application started (ParquetBrokenShutdown.java:178)
2016-02-16 12:39:58.930 DEBUG c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application started (ParquetBrokenShutdown.java:179)
2016-02-16 12:39:58.930 INFO  c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application started (ParquetBrokenShutdown.java:180)
2016-02-16 12:39:58.930 WARN  c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application started (ParquetBrokenShutdown.java:181)
2016-02-16 12:39:58.931 ERROR c.a.b.parquet.ParquetBrokenShutdown [main]: Logging test: application started (ParquetBrokenShutdown.java:182)
2016-02-16 12:39:59.188 DEBUG c.a.b.parquet.ParquetBrokenShutdown [main]: Opening Parquet file: hdfs://nameservice1/user/turek/bugreport.parquet (ParquetBrokenShutdown.java:95)
2016-02-16 12:39:59.335 WARN  o.a.hadoop.util.NativeCodeLoader    [main]: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable (NativeCodeLoader.java:62)
2016-02-16 12:40:00.228 INFO  o.a.hadoop.io.compress.CodecPool    [main]: Got brand-new compressor [.gz] (CodecPool.java:151)
2016-02-16 12:40:00.295 DEBUG c.a.b.parquet.ParquetBrokenShutdown [main]: Parquet file opened: hdfs://nameservice1/user/turek/bugreport.parquet (ParquetBrokenShutdown.java:105)
2016-02-16 12:40:00.297 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:111)
2016-02-16 12:40:01.299 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:111)
2016-02-16 12:40:02.299 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:111)
2016-02-16 12:40:03.301 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:111)
2016-02-16 12:40:03.585 INFO  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: =============== STOPPING APPLICATION =============== (ParquetBrokenShutdown.java:177)
Logging test: stopping application
Logging test: application finished
Logging test: shutdown hook finished

Process finished with exit code 143
```


Output in `test.log` file:

```
2016-02-16 12:39:58.922 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: =============== STARTING APPLICATION ===============
2016-02-16 12:39:58.928 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: starting application
2016-02-16 12:39:58.928 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: starting application
2016-02-16 12:39:58.928 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: starting application
2016-02-16 12:39:58.928 WARN  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: starting application
2016-02-16 12:39:58.928 ERROR c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: starting application
2016-02-16 12:39:58.929 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: =============== APPLICATION STARTED ===============
2016-02-16 12:39:58.930 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application started
2016-02-16 12:39:58.930 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application started
2016-02-16 12:39:58.930 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application started
2016-02-16 12:39:58.930 WARN  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application started
2016-02-16 12:39:58.931 ERROR c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application started
2016-02-16 12:39:59.188 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Opening Parquet file: hdfs://nameservice1/user/turek/bugreport.parquet
2016-02-16 12:39:59.335 WARN  org.apache.hadoop.util.NativeCodeLoader       [main]: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-02-16 12:40:00.228 INFO  org.apache.hadoop.io.compress.CodecPool       [main]: Got brand-new compressor [.gz]
2016-02-16 12:40:00.295 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Parquet file opened: hdfs://nameservice1/user/turek/bugreport.parquet
2016-02-16 12:40:00.297 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Writing record: {"test": "test value"}
2016-02-16 12:40:01.299 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Writing record: {"test": "test value"}
2016-02-16 12:40:02.299 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Writing record: {"test": "test value"}
2016-02-16 12:40:03.301 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Writing record: {"test": "test value"}
2016-02-16 12:40:03.585 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: =============== STOPPING APPLICATION ===============
2016-02-16 12:40:03.585 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: stopping application
2016-02-16 12:40:03.585 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: stopping application
2016-02-16 12:40:03.585 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: stopping application
2016-02-16 12:40:03.585 WARN  c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: stopping application
2016-02-16 12:40:03.586 ERROR c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: stopping application
2016-02-16 12:40:03.586 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Closing instance
2016-02-16 12:40:04.302 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Closing Parquet file: hdfs://nameservice1/user/turek/bugreport.parquet
2016-02-16 12:40:04.514 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Parquet file closed: hdfs://nameservice1/user/turek/bugreport.parquet
2016-02-16 12:40:04.514 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: =============== APPLICATION FINISHED ===============
2016-02-16 12:40:04.514 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application finished
2016-02-16 12:40:04.514 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application finished
2016-02-16 12:40:04.515 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application finished
2016-02-16 12:40:04.515 WARN  c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application finished
2016-02-16 12:40:04.515 ERROR c.a.bugreport.parquet.ParquetBrokenShutdown   [main]: Logging test: application finished
2016-02-16 12:40:04.616 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: =============== SHUTDOWN HOOK FINISHED ===============
2016-02-16 12:40:04.616 TRACE c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: shutdown hook finished
2016-02-16 12:40:04.616 DEBUG c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: shutdown hook finished
2016-02-16 12:40:04.616 INFO  c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: shutdown hook finished
2016-02-16 12:40:04.616 WARN  c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: shutdown hook finished
2016-02-16 12:40:04.617 ERROR c.a.bugreport.parquet.ParquetBrokenShutdown   [Thread-0]: Logging test: shutdown hook finished
```


So somebody either manipulates console appender or closes `System.out` stream.

```
    private static void loggingTest(String description) {
        LOGGER.info("=============== {} ===============", description.toUpperCase());
        LOGGER.trace("Logging test: " + description);
        LOGGER.debug("Logging test: " + description);
        LOGGER.info("Logging test: " + description);
        LOGGER.warn("Logging test: " + description);
        LOGGER.error("Logging test: " + description);
        System.out.println("Logging test: stdout, " + description);    // <<<<< ADDED
        System.err.println("Logging test: stderr, " + description);
    }
```


```
2016-02-16 13:14:22.497 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:111)
2016-02-16 13:14:23.498 TRACE c.a.b.parquet.ParquetBrokenShutdown [main]: Writing record: {"test": "test value"} (ParquetBrokenShutdown.java:111)
2016-02-16 13:14:23.726 INFO  c.a.b.parquet.ParquetBrokenShutdown [Thread-0]: =============== STOPPING APPLICATION =============== (ParquetBrokenShutdown.java:177)
Logging test: stderr, stopping application
Logging test: stderr, application finished
Logging test: stderr, shutdown hook finished

Process finished with exit code 143
```


So somebody closes `System.out`, nice! Put a breakpoint to `java.io.PrintStream.close()` and the winner is... `java.util.logging`, which is used internally in `org.apache.parquet.Log`.

```
"Thread-1@3141" prio=5 tid=0xe nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.io.PrintStream.close(PrintStream.java:355)
	  at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
	  at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
	  - locked <0xc55> (a java.io.OutputStreamWriter)
	  at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
	  at java.util.logging.StreamHandler.flushAndClose(StreamHandler.java:278)
	  - locked <0xc56> (a java.util.logging.StreamHandler)
	  at java.util.logging.StreamHandler.close(StreamHandler.java:302)
	  at java.util.logging.LogManager.resetLogger(LogManager.java:1346)
	  at java.util.logging.LogManager.reset(LogManager.java:1332)
	  at java.util.logging.LogManager$Cleaner.run(LogManager.java:239)
```


It seems workaround from here http://stackoverflow.com/a/13825590 works and can be used as a temporary fix in the application code.

```
public class Main {
    static {
        // must be called before any Logger method is used.
        System.setProperty("java.util.logging.manager", MyLogManager.class.getName());
    }

    public static class MyLogManager extends LogManager {
        static MyLogManager instance;
        public MyLogManager() { instance = this; }
        @Override public void reset() { /* don't reset yet. */ }
        private void reset0() { super.reset(); }
        public static void resetFinally() { instance.reset0(); }
    }

    public static void main(String... args) {
        // ...
    }
}
```

`java.util.logging` dependency is planned to be removed in PARQUET-401, which will be a final fix.

**Comment by asfimport** [comment]
[Michal Turek](https://issues.apache.org/jira/browse/PARQUET-408?#comment-15148545) / @mixalturek:
I'm closing the issue, workaround is known and can be used in the applications and PARQUET-401 will introduce a final fix.
