### ISSUE TITLE
Avoid evoking job.toString() in ParquetLoader

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1942]
When ran under hadoop2 environment and log level setting to _DEBUG_, _ParquetLoader_ would evoke _job.toString()_ in several methods, which might cause the whole application to stop due to :

> java.lang.IllegalStateException: Job in state DEFINE instead of RUNNING
> 
> at org.apache.hadoop.mapreduce.Job.ensureState(Job.java:283)
> at org.apache.hadoop.mapreduce.Job.toString(Job.java:452)
> at java.lang.String.valueOf(String.java:2847)
> at java.lang.StringBuilder.append(StringBuilder.java:128)
> at org.apache.parquet.pig.ParquetLoader.getSchema(ParquetLoader.java:260)
> at org.apache.parquet.pig.TestParquetLoader.testSchema(TestParquetLoader.java:54)
> ...

The reason is that in the hadoop 2.x branch, _org.apache.hadoop.mapreduce.Job.toString()_ has added an _ensureState(JobState.RUNNING)_ check; see map-reduce: Job.java#452. In contrast, the hadoop 1.x branch does not contain such checks, so _ParquetLoader_ works well.

This ticket simply avoids evoking _job.toString()_ in _ParquetLoader_.

**Reporter**: [Liwei Lin(Inactive)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=proflin) / @lw-lin
**Assignee**: [Liwei Lin(Inactive)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=proflin) / @lw-lin
#### Related issues:
- [Deprecate Log and move to SLF4J Logger](https://issues.apache.org/jira/browse/PARQUET-401) (blocks)
#### PRs and other links:
- [PR#326](https://github.com/apache/parquet-mr/pull/326)

<sub>**Note**: *This issue was originally created as [PARQUET-529](https://issues.apache.org/jira/browse/PARQUET-529). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-529?#comment-15156399) / @rdblue:
I committed the fix. Thanks, @lw-lin!
