### ISSUE TITLE
[Java] Upgrade the Apache Arrow version to 0.8.0 for SchemaConverter

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2090]
When I converted parquet(1.9.1-SNAPSHOT) schema to arrow(0.4.0) with SchemaConverter, this exception raised.

```java

java.lang.NoClassDefFoundError: org/apache/arrow/vector/types/pojo/ArrowType$Struct_

	at net.wrap_trap.parquet_arrow.ParquetToArrowConverter.convertToArrow(ParquetToArrowConverter.java:67)
	at net.wrap_trap.parquet_arrow.ParquetToArrowConverter.convertToArrow(ParquetToArrowConverter.java:40)
	at net.wrap_trap.parquet_arrow.ParquetToArrowConverterTest.parquetToArrowConverterTest(ParquetToArrowConverterTest.java:27)
```

This reason is that SchemaConverter refer to Apache Arrow 0.1.0.
I upgrade the Apache Arrow version to 0.8.0 for SchemaConverter.

**Reporter**: [Masayuki Takahashi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=masayuki038) / @masayuki038
**Assignee**: [Masayuki Takahashi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=masayuki038) / @masayuki038
#### PRs and other links:
- [GitHub Pull Request #443](https://github.com/apache/parquet-mr/pull/443)

<sub>**Note**: *This issue was originally created as [PARQUET-1128](https://issues.apache.org/jira/browse/PARQUET-1128). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Masayuki Takahashi](https://issues.apache.org/jira/browse/PARQUET-1128?#comment-16196921) / @masayuki038:
Pull Request: https://github.com/apache/parquet-mr/pull/423

**Comment by asfimport** [comment]
[Masayuki Takahashi](https://issues.apache.org/jira/browse/PARQUET-1128?#comment-16309728) / @masayuki038:
I have canceled PR#423 and recreated it.
New Pull Request: https://github.com/apache/parquet-mr/pull/443

**Comment by asfimport** [comment]
[Andy Grove](https://issues.apache.org/jira/browse/PARQUET-1128?#comment-16446412) / @andygrove:
What is the status of this? I am running into similar issues and would like to help get this resolved.

**Comment by asfimport** [comment]
[Uwe Korn](https://issues.apache.org/jira/browse/PARQUET-1128?#comment-16446811) / @xhochy:
Issue resolved by pull request 443
<https://github.com/apache/parquet-mr/pull/443>
