### ISSUE TITLE
 java.lang.UnsupportedOperationException: Unimplemented type: StringType

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2147]
java.lang.UnsupportedOperationException: Unimplemented type: StringType
 at org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.readIntBatch(VectorizedColumnReader.java:356)
 at org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.readBatch(VectorizedColumnReader.java:183)
 at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextBatch(VectorizedParquetRecordReader.java:230)
 at org.apache.spark.sql.execution.datasources.parquet.VectorizedParquetRecordReader.nextKeyValue(VectorizedParquetRecordReader.java:137)
 at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
 at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1$$anon$2.getNext(FileScanRDD.scala:133)
 at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
 at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
 at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:166)
 at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:102)
 at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.scan_nextBatch$(Unknown Source)
 at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
 at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
 at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
 at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.execute(FileFormatWriter.scala:243)
 at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:190)
 at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:188)
 at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1341)
 at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:193)
 ... 8 more

**Reporter**: [Shrutika modi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=modi.shrutika)

<sub>**Note**: *This issue was originally created as [PARQUET-1248](https://issues.apache.org/jira/browse/PARQUET-1248). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Nándor Kollár](https://issues.apache.org/jira/browse/PARQUET-1248?#comment-16423711) / @nandorKollar:
[~modi.shrutika] based on the information you provided, I think this error is related to vectorized Parquet reader in Spark, and not a Parquet issue. If you take a look at Spark code, there's a TODO in the [readIntBatch](https://github.com/apache/spark/blame/master/sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/VectorizedColumnReader.java#L385) method, maybe the error you got is related to it (however looks like it tries read ints while you have strings)? I'm not familiar with Spark, but maybe you have similar problem like SPARK-23822.

**Comment by asfimport** [comment]
[Yuming Wang](https://issues.apache.org/jira/browse/PARQUET-1248?#comment-16502780) / @wangyum:
[~modi.shrutika], How to reproduce this issue?
