### ISSUE TITLE
"missing LastBuildJobID" error when building new cube segment

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2161]
An unstable exception. Likely to happen when there are multiple concurrent builds.

`2018-04-18 20:11:16,856 ERROR [pool-33-thread-11] threadpool.DefaultScheduler : ExecuteException job:cc08da19-f53e-4344-a6c5-05e764834924`
` org.apache.kylin.job.exception.ExecuteException: org.apache.kylin.job.exception.ExecuteException: java.lang.IllegalStateException: For cube CUBE[name=cube2], segment cube2[2018041423000_2018041423001] missing LastBuildJobID`
` at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:140)`
` at org.apache.kylin.job.impl.threadpool.DefaultScheduler$JobRunner.run(DefaultScheduler.java:307)`
` at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)`
` at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`
` at java.lang.Thread.run(Thread.java:748)`
` Caused by: org.apache.kylin.job.exception.ExecuteException: java.lang.IllegalStateException: For cube CUBE[name=cube2], segment cube2[2018041423000_2018041423001] missing LastBuildJobID`
` at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:140)`
` at org.apache.kylin.job.execution.DefaultChainedExecutable.doWork(DefaultChainedExecutable.java:67)`
` at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:129)`
` ... 4 more`
` Caused by: java.lang.IllegalStateException: For cube CUBE[name=cube2], segment cube2[2018041423000_2018041423001] missing LastBuildJobID`
` at org.apache.kylin.cube.CubeManager$SegmentAssist.promoteNewlyBuiltSegments(CubeManager.java:810)`
` at org.apache.kylin.cube.CubeManager.promoteNewlyBuiltSegments(CubeManager.java:535)`
` at org.apache.kylin.engine.mr.steps.UpdateCubeInfoAfterBuildStep.doWork(UpdateCubeInfoAfterBuildStep.java:78)`
` at io.kyligence.kap.engine.mr.steps.KapUpdateCubeInfoAfterBuildStep.doWork(SourceFile:47)`
` at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:129)`
` ... 6 more`

**Reporter**: [liyang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=liyang.gmt8@gmail.com)

<sub>**Note**: *This issue was originally created as [PARQUET-1282](https://issues.apache.org/jira/browse/PARQUET-1282). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[liyang](https://issues.apache.org/jira/browse/PARQUET-1282?#comment-16451769):
Sorry, wrong project.
