### ISSUE TITLE
ParquetMetadataConverter throw NPE

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2180]
How to reproduce:

```scala

$ bin/spark-shell 
scala> spark.range(10).selectExpr("cast(id as string) as id").coalesce(1).write.parquet("/tmp/parquet-1317")
scala> 

java -jar ./parquet-tools/target/parquet-tools-1.10.1-SNAPSHOT.jar head --debug file:///tmp/parquet-1317/part-00000-6cfafbdd-fdeb-4861-8499-8583852ba437-c000.snappy.parquet
```

```

java.io.IOException: Could not read footer: java.lang.NullPointerException

at org.apache.parquet.hadoop.ParquetFileReader.readAllFootersInParallel(ParquetFileReader.java:271)

at org.apache.parquet.hadoop.ParquetFileReader.readAllFootersInParallelUsingSummaryFiles(ParquetFileReader.java:202)

at org.apache.parquet.hadoop.ParquetFileReader.readFooters(ParquetFileReader.java:354)

at org.apache.parquet.tools.command.RowCountCommand.execute(RowCountCommand.java:88)

at org.apache.parquet.tools.Main.main(Main.java:223)

Caused by: java.lang.NullPointerException

at org.apache.parquet.format.converter.ParquetMetadataConverter.getOriginalType(ParquetMetadataConverter.java:828)

at org.apache.parquet.format.converter.ParquetMetadataConverter.buildChildren(ParquetMetadataConverter.java:1173)

at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetSchema(ParquetMetadataConverter.java:1124)

at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetMetadata(ParquetMetadataConverter.java:1058)

at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1052)

at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:532)

at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:505)

at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:499)

at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:476)

at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:261)

at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:257)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

java.io.IOException: Could not read footer: java.lang.NullPointerException
```

**Reporter**: [Yuming Wang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yumwang) / @wangyum
**Assignee**: [Yuming Wang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yumwang) / @wangyum
#### PRs and other links:
- [GitHub Pull Request #489](https://github.com/apache/parquet-mr/pull/489)
- [GitHub Pull Request #491](https://github.com/apache/parquet-mr/pull/491)

<sub>**Note**: *This issue was originally created as [PARQUET-1317](https://issues.apache.org/jira/browse/PARQUET-1317). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Yuming Wang](https://issues.apache.org/jira/browse/PARQUET-1317?#comment-16499820) / @wangyum:
I'm working on this.

**Comment by asfimport** [comment]
[Nándor Kollár](https://issues.apache.org/jira/browse/PARQUET-1317?#comment-16499887) / @nandorKollar:
Thanks @wangyum for reporting this problem! It looks like this is caused by my recent [change](https://github.com/apache/parquet-mr/commit/94a8bf6d304d08e8a1fc181e7a06a545103e8ddb) related to new logical types API, I'm afraid that there's a missing null check in `getOriginalType` method. Feel free to ask/ping me if you've any question about this issue, and I'm happy to take a look your PR!

**Comment by asfimport** [comment]
[Zoltan Ivanfi](https://issues.apache.org/jira/browse/PARQUET-1317?#comment-16499891) / @zivanfi:
Hi @wangyum, Thanks for reporting and investigating this issue. Since you wrote that you are working on it (but couldn't assign it to yourself due to insufficient access rights), I added you to the list of contributors and assigned the JIRA to you. In the future you can freely assign tickets to yourself (and of course you can unassign them as well if you stop working on them).

**Comment by asfimport** [comment]
[Nándor Kollár](https://issues.apache.org/jira/browse/PARQUET-1317?#comment-16500397) / @nandorKollar:
Created a [PR](https://github.com/apache/parquet-mr/pull/491) to reproduce the issue. Note, it only includes a unit test to reproduce this issue, the fix is in [489](https://github.com/apache/parquet-mr/pull/489).
