### ISSUE TITLE
Data loss on duplicate values with AvroParquetWriter/Reader

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2223]
```java

public class Blah {

  private static Path parquetFile = new Path("oops");
  private static Schema schema = SchemaBuilder.record("spark_schema")
      .fields().optionalBytes("value").endRecord();

  private static GenericData.Record recordFor(String value) {
    return new GenericRecordBuilder(schema)
        .set("value", value.getBytes()).build();
  }

  public static void main(String ... args) throws IOException {
    try (ParquetWriter<GenericData.Record> writer = AvroParquetWriter
          .<GenericData.Record>builder(parquetFile)
          .withSchema(schema)
          .build()) {
      writer.write(recordFor("one"));
      writer.write(recordFor("two"));
      writer.write(recordFor("three"));
      writer.write(recordFor("three"));
      writer.write(recordFor("two"));
      writer.write(recordFor("one"));
      writer.write(recordFor("zero"));
    }

    try (ParquetReader<GenericRecord> reader = AvroParquetReader
        .<GenericRecord>builder(parquetFile)
        .withConf(new Configuration()).build()) {
      GenericRecord rec;
      int i = 0;
      while ((rec = reader.read()) != null) {
        ByteBuffer buf = (ByteBuffer) rec.get("value");
        byte[] bytes = new byte[buf.remaining()];
        buf.get(bytes);
        System.out.println("rec " + i++ + ": " + new String(bytes));
      }
    }
  }
}
```
Expected output:
```

rec 0: one
rec 1: two
rec 2: three
rec 3: three
rec 4: two
rec 5: one
rec 6: zero
```
Actual:
```

rec 0: one
rec 1: two
rec 2: three
rec 3: 
rec 4: 
rec 5: 
rec 6: zero
```
 

This was found when we started getting empty byte[] values back in spark unexpectedly.  (Spark 2.3.1 and Parquet 1.8.3).   I have not tried to reproduce with parquet 1.9.0, but its a bad enough bug that I would like a 1.8.4 release that I can drop-in replace 1.8.3 without any binary compatibility issues.

 Duplicate byte[] values are lost.

 

A few clues: 

If I do not call ByteBuffer.get, the size of ByteBuffer.remaining does not go to zero.  I suspect a ByteBuffer is being recycled, but the call to ByteBuffer.get mutates it.  I wonder if an appropriately placed ByteBuffer.duplicate() would fix it.

 

**Reporter**: [Scott Carey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=scottcarey)
**Assignee**: [Nándor Kollár](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nkollar) / @nandorKollar
#### PRs and other links:
- [GitHub Pull Request #551](https://github.com/apache/parquet-mr/pull/551)
- [GitHub Pull Request #552](https://github.com/apache/parquet-mr/pull/552)

<sub>**Note**: *This issue was originally created as [PARQUET-1407](https://issues.apache.org/jira/browse/PARQUET-1407). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Scott Carey](https://issues.apache.org/jira/browse/PARQUET-1407?#comment-16596941):
adding a call to duplicate() fixes it.

Apparently Spark isn't calling that, if you use its parquet reader to create a DataFrame the same thing happens, values are skipped.  Its a Parquet bug, since GenericRecord.get()'s contract does not indicate that two different instances can return the same ByteBuffer instance.   Parquet should call return a duplicate() if it is re-using underlying data between records.

**Comment by asfimport** [comment]
[Scott Carey](https://issues.apache.org/jira/browse/PARQUET-1407?#comment-16597109):
The same thing happens with 1.9.0

**Comment by asfimport** [comment]
[Jacky Tan](https://issues.apache.org/jira/browse/PARQUET-1407?#comment-16688707):
Same thing with 1.10.0

When there are duplicate BigDecimal records, `AvroParquetReader.read()` will throw an exception:
```java

Can not read value at 2 in block 0 in file file:/.../decimal.parquet
 org.apache.parquet.io.ParquetDecodingException: Can not read value at 2 in block 0 in file file:/.../decimal.parquet
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:251)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)
```
I was able to create a workaround using `[~scottcarey]` suggestion of calling `duplicate()` on the `ByteBuffer`
```java

  private static class NonMutatedByteBufferDecimalConversion extends DecimalConversion {
    @Override
    public BigDecimal fromBytes(final ByteBuffer value, final Schema schema, final LogicalType type) {
      final ByteBuffer byteBuffer = value.duplicate();
      return super.fromBytes(byteBuffer, schema, type);
    }
  }
```
And using it in the reader:
```java

GenericData decimalSupport = new GenericData();
decimalSupport.addLogicalTypeConversion(new NonMutatedByteBufferDecimalConversion());

AvroParquetReader
        .<GenericRecord>builder(path)
        .withDataModel(decimalSupport)
        .build();
```

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-1407?#comment-16688796) / @rdblue:
`[~scottcarey]`, `[~jackytan]`, sorry for the delay. I didn't see this issue until now.

I've posted a PR that should fix it. I haven't written a test for it. If you want to pick that commit and submit a PR with a test, that would be a great way to contribute! If not, I'll get it done sometime soon and this can be fixed in 1.11.0. Thanks!

**Comment by asfimport** [comment]
[Jacky Tan](https://issues.apache.org/jira/browse/PARQUET-1407?#comment-16689448):
Thanks @rdblue!, I'll try to get a test in the next couple days.

**Comment by asfimport** [comment]
[Nándor Kollár](https://issues.apache.org/jira/browse/PARQUET-1407?#comment-16692014) / @nandorKollar:
@rdblue `[~scottcarey]` `[~jackytan]`  I added a unit test to Ryan's fix. Could you please review PR #552?
