### ISSUE TITLE
[C++] corrupted files produced on 32-bit architecture (i686)

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2237]
I'm using C++ API to convert some data to parquet files. I've noticed a regression when upgrading from arrow-cpp 0.10.0 + parquet-cpp 1.5.0 to arrow-cpp 0.11.0. The issue is that I can write parquet files without an error, but when I try to read those using pyarrow I get a segfault:

```

#0  0x00007fffd17c7f0f in int arrow::util::RleDecoder::GetBatchWithDictSpaced<float>(float const*, float*, int, int, unsigned char const*, long) ()
   from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
#1  0x00007fffd17c8025 in parquet::DictionaryDecoder<parquet::DataType<(parquet::Type::type)4> >::DecodeSpaced(float*, int, int, unsigned char const*, long) ()
   from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
#2  0x00007fffd17bcf0f in parquet::internal::TypedRecordReader<parquet::DataType<(parquet::Type::type)4> >::ReadRecordData(long) ()
   from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
#3  0x00007fffd17bfbea in parquet::internal::TypedRecordReader<parquet::DataType<(parquet::Type::type)4> >::ReadRecords(long) ()
   from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
#4  0x00007fffd179d2f7 in parquet::arrow::PrimitiveImpl::NextBatch(long, std::shared_ptr<arrow::Array>*) ()
   from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
#5  0x00007fffd1797162 in parquet::arrow::ColumnReader::NextBatch(long, std::shared_ptr<arrow::Array>*) ()
   from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
#6  0x00007fffd179a6e5 in parquet::arrow::FileReader::Impl::ReadSchemaField(int, std::vector<int, std::allocator<int> > const&, std::shared_ptr<arrow::Array>*) ()
   from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
#7  0x00007fffd179aaad in parquet::arrow::FileReader::Impl::ReadTable(std::vector<int, std::allocator<int> > const&, std::shared_ptr<arrow::Table>*)::{lambda(int)#1}::operator()(int) const () from /nix/store/k6sy2ncjnkn5wnb2dq9m5f0qh446kjhg-arrow-cpp-0.11.0/lib/libparquet.so.11
```

I have not been able to dig to the bottom of the issue, but it seems like the problem reproduces only when I run 32 bit binaries. After I learned that, I found that 32 bit and 64 bit codes produce very different different parquet files for the same data. The sizes of the structures are clearly different if I look at their hexdumps. I'm attaching those example files. Reading "32.parquet" (produced using i686 binaries) will cause a segfault on macOS and linux, "64.parquet" will read just fine.

**Reporter**: [Dmitry Kalinkin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=veprbl) / @veprbl
#### Original Issue Attachments:
- [32.parquet](https://issues.apache.org/jira/secure/attachment/12942953/32.parquet)
- [64.parquet](https://issues.apache.org/jira/secure/attachment/12942952/64.parquet)
- [arrow_0.10.0_i686_test_fail.log](https://issues.apache.org/jira/secure/attachment/12943087/arrow_0.10.0_i686_test_fail.log)
- [arrow_0.11.0_i686_test_fail.log](https://issues.apache.org/jira/secure/attachment/12943088/arrow_0.11.0_i686_test_fail.log)
- [parquet_1.5.0_i686_test_success.log](https://issues.apache.org/jira/secure/attachment/12943089/parquet_1.5.0_i686_test_success.log)

<sub>**Note**: *This issue was originally created as [PARQUET-1438](https://issues.apache.org/jira/browse/PARQUET-1438). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16642990) / @wesm:
Since we do not test or develop on 32-bit arch, I would guess that it's not very well supported in general. We would appreciate some help with this

**Comment by asfimport** [comment]
[Dmitry Kalinkin](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643415) / @veprbl:
I now checked files that were produced with previous version of the parquet-cpp 1.5.0 on 32 bit and they mostly match what I get on 64 bit arrow-cpp 0.11.0. I also tried to do a bisect on arrow-cpp repository, but could not find any good commit. They all either have the bug or don't build. I guess, I could try to bisect paquet-cpp repository against arrow-cpp 0.10.0.

I was hoping someone with the knowledge of the format could take a look at files and see which part of the structure blows up. It seems like it is the schema that blows up. That means I need to look at thrift related stuff?

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643440) / @wesm:
Are you using the _released_ version of 1.5.0 or some other version? There should be little discrepancy between the code in parquet-cpp 1.5.0 and what's in master now

**Comment by asfimport** [comment]
[Dmitry Kalinkin](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643462) / @veprbl:
Yes. The setup with arrow-cpp 0.10.0 and parquet-cpp 1.5.0 uses the tarball from https://github.com/apache/parquet-cpp/archive/apache-parquet-cpp-1.5.0.tar.gz

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643525) / @wesm:
Here's the effective diff on the codebases

https://gist.github.com/wesm/e8e43aba036db747fb9c021d590be938

Is it possible you have a conflicting libparquet.so lying around? 

The only thing that looks possibly concerning are some changes to the metadata introduced in PARQUET-1369. If you build with the commit 3545186d6 right before that, do you still get the issue? If you want to git bisect, the place to start is 9b4cd9c03 ARROW-3075

**Comment by asfimport** [comment]
[Dmitry Kalinkin](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643608) / @veprbl:
Thank you for providing the diff. I looked and it doesn't seem very drastic to me as well.

I don't think there is a conflicting libraries problem. I do all of my builds in a sandbox and the writing of files does succeed with resulting files being grossly different for 0.11.0 on 32 bits.

Unfortunately all of 3545186d6, 3545186d6~ and 9b4cd9c03 do reproduce the bug.

**Comment by asfimport** [comment]
[Wes McKinney](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643674) / @wesm:
If you can provide a way to reproduce the problem such that one of us can debug with gdb, that would be helpful. I personally don't have the bandwidth to debug this. Does the test suite pass on 32-bit?

**Comment by asfimport** [comment]
[Dmitry Kalinkin](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643963) / @veprbl:
Running test suite was a great suggestion!

I've tested arrow-cpp 0.10.0, parquet 1.5.0, arrow-cpp 0.11.0 and found that all tests pass on x86_64. As for tests on i686, **1** test fail on arrow-cpp 0.10.0, **0** failures for parquet 1.5.0 (against arrow-cpp 0.10.0), arrow-cpp 0.11.0 has **11** failing tests. I'm attaching log files to the ticket.

**Comment by asfimport** [comment]
[Dmitry Kalinkin](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16643970) / @veprbl:
Perhaps this is an arrow issue then?

**Comment by asfimport** [comment]
[Dmitry Kalinkin](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16644052) / @veprbl:
Opened ARROW-3477

**Comment by asfimport** [comment]
[Dmitry Kalinkin](https://issues.apache.org/jira/browse/PARQUET-1438?#comment-16770329) / @veprbl:
This got resolved after fixing the issue in arrow-cpp
