### ISSUE TITLE
[parquet-cli] Argument error: Illegal character in opaque part at index 2 on Windows

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2305]
Some commands of parquet-cli don't work on Windows.

```Java

$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main schema C:\Users\masayuki\Downloads\test.parquet                                                               Argument error: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.parquet          
                                    
$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main csv-schema C:\Users\masayuki\Downloads\test.csv --record-name Test                                              
Argument error: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.csv              

$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main convert-csv C:\Users\masayuki\Downlo ads\test.csv -o C:\Users\masayuki\Downloads\test-csv.parquet
Argument error: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.csv

$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main convert C:\Users\masayuki\Downloads\ userdata1.avro -o C:\Users\masayuki\Downloads\userdata1.parquet
Argument error: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\userdata1.avro

$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main to-avro C:\Users\masayuki\Downloads\ test.parquet -o C:\Users\masayuki\Downloads\test.avro
Argument error: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.parquet

$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main cat C:\Users\masayuki\Downloads\test.parquet
Argument error: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.parquet

$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main head -n 10 C:\Users\masayuki\Downloa ds\test.parquet
Argument error: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.parquet
```

The following commands work on Windows.

- meta
- pages
- check-stats
- column-index

**Reporter**: [Masayuki Takahashi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=masayuki038) / @masayuki038
**Assignee**: [Masayuki Takahashi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=masayuki038) / @masayuki038
#### PRs and other links:
- [GitHub Pull Request #627](https://github.com/apache/parquet-mr/pull/627)

<sub>**Note**: *This issue was originally created as [PARQUET-1534](https://issues.apache.org/jira/browse/PARQUET-1534). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Masayuki Takahashi](https://issues.apache.org/jira/browse/PARQUET-1534?#comment-16773974) / @masayuki038:
The stacktrace is following:
```Java

$ java -cp target/classes;target/dependency/* org.apache.parquet.cli.Main --verbose cat C:\Users\masayuki\Down loads\test.parquet
Argument error
java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.parquet
        at java.net.URI.create(Unknown Source)
        at org.apache.parquet.cli.BaseCommand.qualifiedURI(BaseCommand.java:178)
        at org.apache.parquet.cli.BaseCommand.getAvroSchema(BaseCommand.java:379)
        at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:66)
        at org.apache.parquet.cli.Main.run(Main.java:147)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.parquet.cli.Main.main(Main.java:177)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\masayuki\Downloads\test.parquet
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        ... 7 more
```
java.net.URI.create throws IllegalArgumentException.
