### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2307]
Hi

I'm writing protobuf to Parquet using ProtoParquetWriter, i'm also writing to local HDFS and write only  one file.

my code running in a bit data environment.

the problem is that after about 30 min of run i'm starting to get exception like this:

 

java.lang.ClassCastException: org.apache.parquet.io.MessageColumnIO cannot be cast to org.apache.parquet.io.PrimitiveColumnIO
 at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.getColumnWriter(MessageColumnIO.java:432)
 at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addLong(MessageColumnIO.java:449)
 at org.apache.parquet.proto.ProtoWriteSupport$LongWriter.writeRawValue(ProtoWriteSupport.java:294)
 at org.apache.parquet.proto.ProtoWriteSupport$FieldWriter.writeField(ProtoWriteSupport.java:145)
 at org.apache.parquet.proto.ProtoWriteSupport$MessageWriter.writeAllFields(ProtoWriteSupport.java:229)
 at org.apache.parquet.proto.ProtoWriteSupport$MessageWriter.writeTopLevelMessage(ProtoWriteSupport.java:194)

 

I printed the message that cause to this error and I can't see any problem with it.

any idea?

 

**Reporter**: [the coder](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=theCoder)

<sub>**Note**: *This issue was originally created as [PARQUET-1541](https://issues.apache.org/jira/browse/PARQUET-1541). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Qinghui Xu](https://issues.apache.org/jira/browse/PARQUET-1541?#comment-16780293) / @qinghui-xu:
Hello, `[~theCoder]`

Could you provide your protobuf schema? Also, what version of parquet-mr are you using?
