### ISSUE TITLE
Possible over-shading of modules

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2310]
When upgrading Apache Iceberg to use what's effectively the master branch of Parquet, we hit this stack trace in one of the unit tests:

 

`java.lang.NoSuchMethodError: org.apache.avro.Schema.setLogicalType(Lorg/apache/avro/LogicalType;)V at org.apache.avro.LogicalType.addToSchema(LogicalType.java:72) at com.netflix.iceberg.avro.TypeToSchema.<clinit>(TypeToSchema.java:42) at com.netflix.iceberg.avro.AvroSchemaUtil.convert(AvroSchemaUtil.java:69) at com.netflix.iceberg.avro.AvroSchemaUtil.convert(AvroSchemaUtil.java:65) at com.netflix.iceberg.PartitionData.getSchema(PartitionData.java:38) at com.netflix.iceberg.PartitionData.<init>(PartitionData.java:67) at com.netflix.iceberg.DataFiles.newPartitionData(DataFiles.java:41) at com.netflix.iceberg.DataFiles.access$000(DataFiles.java:36) at com.netflix.iceberg.DataFiles$Builder.<init>(DataFiles.java:225) at com.netflix.iceberg.DataFiles.builder(DataFiles.java:191) at com.netflix.iceberg.hive.HiveTablesTest.testConcurrentFastAppends(HiveTablesTest.java:108) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) at org.junit.runners.ParentRunner.run(ParentRunner.java:363) at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110) at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58) at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38) at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62) at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) at com.sun.proxy.$Proxy2.processTestClass(Unknown Source) at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175) at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157) at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404) at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) at java.lang.Thread.run(Thread.java:748)`

At first it's not immediately obvious if this is a problem in Iceberg's dependency chain, or if it's a problem in how parquet-avro is packaged. But I'm filing here because it appears linked to PARQUET-1529, where we shaded FastUtil in various modules, including parquet-avro. A hypothesis is that applying the shading plugin caused references to Jackson 1 to be shaded as well, and that libraries that depend on both parquet-avro and Avro itself (as Iceberg does) are at risk of having mismatching implementations being loaded on the classpath.

 

**Reporter**: [Matt Cheah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcheah) / @mccheah
**Assignee**: [Gabor Szadovszky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gszadovszky) / @gszadovszky
#### PRs and other links:
- [GitHub Pull Request #628](https://github.com/apache/parquet-mr/pull/628)

<sub>**Note**: *This issue was originally created as [PARQUET-1544](https://issues.apache.org/jira/browse/PARQUET-1544). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Matt Cheah](https://issues.apache.org/jira/browse/PARQUET-1544?#comment-16792924) / @mccheah:
For an example of the failure, see [this build](https://circleci.com/gh/palantir/incubator-iceberg/2?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). which was in an attempt to [upgrade Parquet in Iceberg](https://github.com/palantir/incubator-iceberg/pull/5). I wonder if we weren't supposed to shade Jackson as well, but applying the maven shade plugin inadvertently caused that to happen?

**Comment by asfimport** [comment]
[Matt Cheah](https://issues.apache.org/jira/browse/PARQUET-1544?#comment-16792932) / @mccheah:
Tagging @gszadovszky @rdblue

**Comment by asfimport** [comment]
[Matt Cheah](https://issues.apache.org/jira/browse/PARQUET-1544?#comment-16793076) / @mccheah:
I confirmed this isn't specific to Palantir's fork of Spark and would apply if we took Parquet's master branch as a dependency directly:
1. Checkout upstream master
1. mvn install
1. Make Iceberg depend on parquet 1.12.0-SNAPSHOT from the local Maven repository
1. `./gradlew test` fails with the same error.

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1544?#comment-16795002) / @gszadovszky:
@mccheah,

Thanks a lot for bringing this up. I confirm that PARQUET-1529 caused the regression that some Avro API calls broke because of shading `jackson` in `parquet-avro`. I've created the PR [#628](https://github.com/apache/parquet-mr/pull/628) to fix this issue. Could you please check if it fixes your problem?
