### ISSUE TITLE
Integer overflow in ParquetFileReader.ConsecutiveChunkList

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2355]
When reading a large Parquet file (2.8GB), I encounter the following exception:
```java

Caused by: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file dbfs:/user/hive/warehouse/demo.db/test_table/part-00014-tid-1888470069989036737-593c82a4-528b-4975-8de0-5bcbc5e9827d-10856-1-c000.snappy.parquet
at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:251)
at org.apache.parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:207)
at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:40)
at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1$$anon$2.getNext(FileScanRDD.scala:228)
... 14 more
Caused by: java.lang.IllegalArgumentException: Illegal Capacity: -212
at java.util.ArrayList.<init>(ArrayList.java:157)
at org.apache.parquet.hadoop.ParquetFileReader$ConsecutiveChunkList.readAll(ParquetFileReader.java:1169)
```
 

The file metadata is:
- block 1 (3 columns)
  
  - rowCount: 110,100
    
  - totalByteSize: 348,492,072
    
  - compressedSize: 165,689,649
    
- block 2 (3 columns)
  
  - rowCount: 90,054
    
  - totalByteSize: 3,243,165,541
    
  - compressedSize: 2,509,579,966
    
- block 3 (3 columns)
  
  - rowCount: 105,119
    
  - totalByteSize: 350,901,693
    
  - compressedSize: 144,952,177
    
- block 4 (3 columns)
  
  - rowCount: 48,741
    
  - totalByteSize: 1,275,995
    
  - compressedSize: 914,205
    
    I don't have the code to reproduce the issue, unfortunately; however, I looked at the code and it seems that integer `length` field in ConsecutiveChunkList overflows, which results in negative capacity for array list in `readAll` method:
    ```java
    
    int fullAllocations = length / options.getMaxAllocationSize();
    int lastAllocationSize = length % options.getMaxAllocationSize();
    	
    int numAllocations = fullAllocations + (lastAllocationSize > 0 ? 1 : 0);
    List<ByteBuffer> buffers = new ArrayList<>(numAllocations);
    ```
     
    
    This is caused by cast to integer in `readNextRowGroup` method in ParquetFileReader:
    ```java
    
    currentChunks.addChunk(new ChunkDescriptor(columnDescriptor, mc, startingPos, (int)mc.getTotalSize()));
    ```
    which overflows when total size of the column is larger than Integer.MAX_VALUE.
    
    I would appreciate if you could help addressing the issue. Thanks!
    
     

**Reporter**: [Ivan Sadikov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sadikovi) / @sadikovi
**Assignee**: [Edward Wright](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=edw_vtxa)

<sub>**Note**: *This issue was originally created as [PARQUET-1633](https://issues.apache.org/jira/browse/PARQUET-1633). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1633?#comment-16901963) / @gszadovszky:
However, parquet-mr do not catch the overflow properly I would not say it is a bug it cannot read this file. A row-group should be able to fit in memory. From Java point of view we can only use a `byte[]` or a `ByteBuffer` of the size a bit below `2^31^` so, a row-group of the size ~3GB (uncompressed size) seems to be too large. Of course, it is possible to handle such large row-groups but it would require significant efforts to rewrite the related code paths and I am not sure we should.
I think, the problem is not that we cannot read this file but that we should never write such large row-groups. What tools did you use to create this file and with what configuration? It is very strange that the 1st row-group is ~350M and the 3rd one as well while the 2nd one is almost 10 times bigger.

**Comment by asfimport** [comment]
[Ivan Sadikov](https://issues.apache.org/jira/browse/PARQUET-1633?#comment-16902096) / @sadikovi:
I would say it is a bug. There are a few instances of overflow I found in parquet-mr, another example being https://issues.apache.org/jira/browse/PARQUET-1632.

I also have a simple repro with Spark; by the way, if you make records shorter, the problem still persists:
```java

import org.apache.spark.sql.functions._

val large_str = udf(() => "a" * (128 * 1024 * 1024))

val df = spark.range(0, 20, 1, 1).withColumn("large_str", large_str())

spark.conf.set("parquet.enable.dictionary", "false")
spark.conf.set("parquet.page.size.row.check.min", "1") // this is done so I don't hit PARQUET-1632
df.write.option("compression", "uncompressed").mode("overwrite").parquet("/mnt/large.parquet")

spark.read.parquet("/mnt/large.parquet").foreach(_ => Unit) // Fails
```
Here is the stacktrace:
```java

org.apache.spark.SparkException: Job aborted due to stage failure: Task 10 in stage 22.0 failed 4 times, most recent failure: Lost task 10.3 in stage 22.0 (TID 121, 10.0.217.97, executor 1): java.lang.IllegalArgumentException: Illegal Capacity: -191
at java.util.ArrayList.<init>(ArrayList.java:157) at org.apache.parquet.hadoop.ParquetFileReader$ConsecutiveChunkList.readAll(ParquetFileReader.java:1169) at org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:811)
```
 

Well, there is no restriction on row group size in parquet format. Also, it is not a significant effort to patch this issue - making ChunkDescriptor size field as well as ConsecutiveChunkList length to have long type should patch this problem (it already has long type in metadata).

**Comment by asfimport** [comment]
[Adrian Ionescu](https://issues.apache.org/jira/browse/PARQUET-1633?#comment-16903730):
I agree with @sadikovi here: Being able to write a file that is then unreadable is a pretty serious bug (i.e. data corruption).
