### ISSUE TITLE
Invalid SchemaException for UUID while using AvroParquetWriter

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2380]
Hi,

I am getting org.apache.parquet.schema.InvalidSchemaException: Cannot write a schema with an empty group: optional group id {} while I include a UUID field on my POJO object. Without UUID everything worked fine. I have seen Parquet suports UUID as part of [#PR-71] on 2.4 release. 
 But I am getting InvalidSchemaException on UUID. Is there anything that I am missing or its a known issue?

**My setup details:**

**gradle dependency :**

dependencies

{ compile group: 'org.springframework.boot', name: 'spring-boot-starter' compile group: 'org.projectlombok', name: 'lombok', version: '1.16.6' compile group: 'com.amazonaws', name: 'aws-java-sdk-bundle', version: '1.11.271' compile group: 'org.apache.parquet', name: 'parquet-avro', version: '1.10.1' compile group: 'org.apache.hadoop', name: 'hadoop-common', version: '3.1.1' compile group: 'org.apache.hadoop', name: 'hadoop-aws', version: '3.1.1' compile group: 'org.apache.hadoop', name: 'hadoop-client', version: '3.1.1' compile group: 'joda-time', name: 'joda-time' compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.6.5' compile group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-joda', version: '2.6.5' }

**Model used:**

@Data
 public class Employee

{ private UUID id; private String name; private int age; private Address address; }

@Data
 public class Address

{ private String streetName; private String city; private Zip zip; }

@Data
 public class Zip

{ private int zip; private int ext; }

 

<u>**My Serializer Code:**</u>

public void serialize(List<D> inputDataToSerialize, CompressionCodecName compressionCodecName) throws IOException {

Path path = new Path("s3a://parquetpoc/data_"+<u>compressionCodecName</u>+".parquet");
 Class clazz = inputDataToSerialize.get(0).getClass();

try (ParquetWriter<D> writer = AvroParquetWriter.<D>builder(path)
 .withSchema(ReflectData.AllowNull.get().getSchema(clazz)) // generate nullable fields
 .withDataModel(ReflectData.get())
 .withConf(parquetConfiguration)
 .withCompressionCodec(compressionCodecName)
 .withWriteMode(OVERWRITE)
 .withWriterVersion(ParquetProperties.WriterVersion.PARQUET_2_0)
 .build()) {

for (D input : inputDataToSerialize)

{ writer.write(input); }

}
 }

private List<Employee> **getInputDataToSerialize**(){
Address address = new Address();
address.setStreetName("Murry Ridge Dr");
address.setCity("Murrysville");
Zip zip = new Zip();
zip.setZip(15668);
zip.setExt(1234);

address.setZip(zip);

List<Employee> employees = new ArrayList<>();

IntStream.range(0, 100000).forEach(i->

{ Employee employee = new Employee(); // employee.setId(UUID.randomUUID()); employee.setAge(20); employee.setName("Test"+i); employee.setAddress(address); employees.add(employee); }

);
return employees;
}

_\*\*Where generic Type D is Employee_

**Reporter**: [Felix Kizhakkel Jose](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=FelixKJose) / @FelixKJose

<sub>**Note**: *This issue was originally created as [PARQUET-1679](https://issues.apache.org/jira/browse/PARQUET-1679). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Felix Kizhakkel Jose](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16954634) / @FelixKJose:
Could someone please help me on this? I am totally blocked with my analysis of data format comparison because UUID is a mandatory field in all my data models

**Comment by asfimport** [comment]
[Qinghui Xu](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16954915) / @qinghui-xu:
Do you have a stacktrace or something?

**Comment by asfimport** [comment]
[Felix Kizhakkel Jose](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16954922) / @FelixKJose:
org.apache.parquet.schema.InvalidSchemaException: Cannot write a schema with an empty group: required group id \{org.apache.parquet.schema.InvalidSchemaException: Cannot write a schema with an empty group: required group id {} at org.apache.parquet.schema.TypeUtil$1.visit(TypeUtil.java:27) at org.apache.parquet.schema.GroupType.accept(GroupType.java:226) at org.apache.parquet.schema.TypeUtil$1.visit(TypeUtil.java:31) at org.apache.parquet.schema.TypeUtil$1.visit(TypeUtil.java:37) at org.apache.parquet.schema.MessageType.accept(MessageType.java:55) at org.apache.parquet.schema.TypeUtil.checkValidWriteSchema(TypeUtil.java:23) at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:233) at org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:280) at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:535) at com.philips.felix.parquet.ParquetDataSerializer.serialize(ParquetDataSerializer.java:64) at com.philips.felix.parquet.Application.run(Application.java:62) at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:800) at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:784) at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771) at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) at com.philips.felix.parquet.Application.main(Application.java:37)

**Comment by asfimport** [comment]
[Qinghui Xu](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16954937) / @qinghui-xu:
It seems that your schema builder (`ReflectData`) takes `UUID` as an ordinary class, and tries to use the its fields as part of the schema. Maybe you should use a byte array for the uuid field.

**Comment by asfimport** [comment]
[Felix Kizhakkel Jose](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16954944) / @FelixKJose:
Hi [~q.xu], 
 Thank you for the quick response. Could you please give me a sample or could you give me snippet on what you mentioned?

PS: The model I have is already defined and used by other consumers, so I cannot modify the model

**Comment by asfimport** [comment]
[Qinghui Xu](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16956236) / @qinghui-xu:
According to the specification (<https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#uuid>), uuid is a logical type which is just some binaries behind the scene. You could just use a `byte[]` instead of `UUID` for your `id` field.

**Comment by asfimport** [comment]
[Felix Kizhakkel Jose](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16956249) / @FelixKJose:
When you mention _"You could just use a `byte[]` instead of `UUID` for your `id` field.", do you mean I have to change the type of the id field in model to byte[] instead of UUID for example:_

@Data
 public class Employee

{ private byte[] id; private String name; private int age; private Address address; }

_instead of :_
 @Data
 public class Employee

{ private UUID id; private String name; private int age; private Address address; }

If yes, then updating model is not a viable solution for me, since this model's been used by other consumers as well

**Comment by asfimport** [comment]
[Felix Kizhakkel Jose](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16961429) / @FelixKJose:
[~q.xu] what do you think?

**Comment by asfimport** [comment]
[Qinghui Xu](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16961457) / @qinghui-xu:
Sorry for the delay.

Yes, you got it right about my previous comment.

If in your case the model must stay unchanged, I see two ways to address it:
- Have a sibling class beside your `Employee`:
  ```java
  
  public class SerializableEmployee {
    private byte[] id; private String name; private int age; private Address address;
  } 
  ```
  Use this class for parquet read/write, and then convert it to/from your `Employee`
- Fix your converter, it seems that you are using Avro converter to convert your java class to parquet schema and that it treats an `UUID` field as a struct. While I'm not expert in Avro, I would expect there might be a way to customize this behavior and to take the `UUID` as some fixed length byte array.

**Comment by asfimport** [comment]
[Felix Kizhakkel Jose](https://issues.apache.org/jira/browse/PARQUET-1679?#comment-16967620) / @FelixKJose:
Hi [~q.xu],
Thank you so much. Do you know whether there is any Converter [Parquet Converter] instead of AvroConverter? I couldn't find one. Could you please provide some insights?
