### ISSUE TITLE
Parquet file in invalid state while writing to S3 when calling ParquetWriter.write

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2444]
This may be related to PARQUET-632. I am also writing parquet to S3, but I am calling ParquetWriter.write directly. I have multiple containerized instances consuming messages from Kafka, converting them to Parquet, and then writing to S3. One instance will begin to throw this exception for all new messages. Sometimes, the container will recover. Other times, it must be restarted manually to recover. I am unable to find any "error thrown previously."

Exception:
 java.io.IOException
 Message:
 The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: BLOCK
 Stacktrace:
```java

org.apache.parquet.hadoop.ParquetFileWriter$STATE.error(ParquetFileWriter.java:168)org.apache.parquet.hadoop.ParquetFileWriter$STATE.startBlock(ParquetFileWriter.java:160)org.apache.parquet.hadoop.ParquetFileWriter.startBlock(ParquetFileWriter.java:291)org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:171)org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:114)org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:308)
```

**Reporter**: [Tristan Davolt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tdavolt)

<sub>**Note**: *This issue was originally created as [PARQUET-1773](https://issues.apache.org/jira/browse/PARQUET-1773). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Brian Mwambazi](https://issues.apache.org/jira/browse/PARQUET-1773?#comment-17021081) / @brimzi:
A full stack trace would be great. Also how are you calling ParquetWriter.write and ParquetWriter.close in your code?

**Comment by asfimport** [comment]
[Tristan Davolt](https://issues.apache.org/jira/browse/PARQUET-1773?#comment-17021281):
Full stack trace:
```java

1/22/2020 8:37:42 AM2020-01-22 15:37:42.241 ERROR [des-sss-applog-consumer,,,] 132 --- [pool-1-thread-1] c.d.e.h.ApplogConsumerMessageHandler     : Exception : java.lang.IllegalArgumentException: You cannot call toBytes() more than once without calling reset()1/22/2020 8:37:42 AM2020-01-22 15:37:42.241 ERROR [des-sss-applog-consumer,,,] 132 --- [pool-1-thread-1] c.d.e.h.ApplogConsumerMessageHandler     : Exception : java.lang.IllegalArgumentException: You cannot call toBytes() more than once without calling reset()1/22/2020 8:37:42 AM at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)1/22/2020 8:37:42 AM at org.apache.parquet.column.values.rle.RunLengthBitPackingHybridEncoder.toBytes(RunLengthBitPackingHybridEncoder.java:254)1/22/2020 8:37:42 AM at org.apache.parquet.column.values.rle.RunLengthBitPackingHybridValuesWriter.getBytes(RunLengthBitPackingHybridValuesWriter.java:65)1/22/2020 8:37:42 AM at org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:148)1/22/2020 8:37:42 AM at org.apache.parquet.column.impl.ColumnWriterV1.accountForValueWritten(ColumnWriterV1.java:106)1/22/2020 8:37:42 AM at org.apache.parquet.column.impl.ColumnWriterV1.write(ColumnWriterV1.java:200)1/22/2020 8:37:42 AM at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:469)1/22/2020 8:37:42 AM at org.apache.parquet.avro.AvroWriteSupport.writeValueWithoutConversion(AvroWriteSupport.java:346)1/22/2020 8:37:42 AM at org.apache.parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:278)1/22/2020 8:37:42 AM at org.apache.parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:191)1/22/2020 8:37:42 AM at org.apache.parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:165)1/22/2020 8:37:42 AM at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:128)1/22/2020 8:37:42 AM at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:299)1/22/2020 8:37:42 AM at com.test.es.writers.ParquetS3Writer.write(ParquetS3Writer.java:250)1/22/2020 8:37:42 AM at com.test.es.handler.ApplogConsumerMessageHandler.processMessage(ApplogConsumerMessageHandler.java:60)1/22/2020 8:37:42 AM at com.test.des.kafka.StreamConsumer.consumeMessage(StreamConsumer.java:160)1/22/2020 8:37:42 AM at com.test.des.kafka.StreamConsumer.run(StreamConsumer.java:97)1/22/2020 8:37:42 AM at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)1/22/2020 8:37:42 AM at java.util.concurrent.FutureTask.run(FutureTask.java:266)1/22/2020 8:37:42 AM at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)1/22/2020 8:37:42 AM at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)1/22/2020 8:37:42 AM at java.lang.Thread.run(Thread.java:748)
```
We've created a custom class (ParquetS3Writer) that initializes an instance of AvroParquetWriter called parquetWriter. Our Kafka consumer creates an instantiation of ParquetS3Writer. ParquetS3Writer.write calls parquetWriter.write and passes a Generic Data Record, which ultimately calls ParquetWriter.write with this record. Every time we call ParquetWriter.write, we increment a counter to keep track of the number of payloads we've written. We have a set buffer size. When the counter reaches that buffer size, we call ParquetWriter.close, then initialize a new AvroParquetWriter and repeat the process.

The exception starts throwing after running for a while without any issues. It exceeds the buffer size and repeats the cycle above many times without failing. It might be worth mentioning that we are processing 5-15k messages per minutes using this message.

**Comment by asfimport** [comment]
[Brian Mwambazi](https://issues.apache.org/jira/browse/PARQUET-1773?#comment-17021349) / @brimzi:
This trace looks somewhat different from the original snippet we have in the bug report. But from what I am seeing both errors somehow are arising from an _Illegal State_ type of error. Since this is not deterministic my guess is you may be having a race condition in your application, particularly on _ParquetS3Writer_

**Comment by asfimport** [comment]
[Tristan Davolt](https://issues.apache.org/jira/browse/PARQUET-1773?#comment-17021619):
I think I may have found the issue, but tell me if you think this is valid. We have a timer that calls parquetWriter.close() and flushes everything to S3 every once in a while for consumers with less traffic, just to make sure we're sending data in a timely manner. I found a moment when a message was received and processed within the same millisecond as the timer task. The received message called parquetWriter.write(). I believe the race condition has something to do with shared resources at the InternalParquetRecordWriter level.

We also see a NPE when this issue begins. Both .close() and .write() eventually call flushRowGroupToStore(). If they are accessing the same resources, the NPE may occur when one thread sets columnStore or pageStore to null, but the other is still trying to access them.

Before throwing the error, flushRowGroupToStore calls startBlock, then it fails and never call endBlock(). Thus it enters the BLOCK state without ever being freed and ever call afterward fails.

Is this a valid theory? I don't currently have a stacktrace for the NPE, but I'll send an update if I get one.

**Comment by asfimport** [comment]
[Brian Mwambazi](https://issues.apache.org/jira/browse/PARQUET-1773?#comment-17021625) / @brimzi:
Yes that sounds like the issue.  _ParquetWriter_  should be used by one thread only. So calls to **write/close** method should not be concurrent since like you found _flushRowGroupToStore_ is called once in a while to flush the row group.

**Comment by asfimport** [comment]
[Tristan Davolt](https://issues.apache.org/jira/browse/PARQUET-1773?#comment-17200413):
It appears the issue was indeed due to the race condition mentioned above. Adding a locking mechanism _ParquetWriter_ seems to have resolved the issue. In addition, we are no longer receiving the error reported in PARQUET-632.

**Comment by asfimport** [comment]
[Tristan Davolt](https://issues.apache.org/jira/browse/PARQUET-1773?#comment-17200415):
This was caused by an implementation issue. _ParquetWriter_ should only be accessible by one thread by design.
