### ISSUE TITLE
ParquetMetadataConveter throws NPE in an Iceberg unit test

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2487]
When writing data to parquet in an Iceberg unit test, it throws NPE as below
```java

java.lang.NullPointerExceptionjava.lang.NullPointerException at org.apache.parquet.format.converter.ParquetMetadataConverter.addRowGroup(ParquetMetadataConverter.java:476) at org.apache.parquet.format.converter.ParquetMetadataConverter.toParquetMetadata(ParquetMetadataConverter.java:177) at org.apache.parquet.hadoop.ParquetFileWriter.serializeFooter(ParquetFileWriter.java:914) at org.apache.parquet.hadoop.ParquetFileWriter.end(ParquetFileWriter.java:864) at org.apache.iceberg.parquet.ParquetWriter.close(ParquetWriter.java:206) at org.apache.iceberg.data.TestLocalScan.writeFile(TestLocalScan.java:429)
```
 

**Reporter**: [Junjie Chen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=junjie) / @chenjunjiedada
**Assignee**: [Junjie Chen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=junjie) / @chenjunjiedada
#### Related issues:
- [Allow empty row in parquet file](https://issues.apache.org/jira/browse/PARQUET-2026) (breaks)

<sub>**Note**: *This issue was originally created as [PARQUET-1851](https://issues.apache.org/jira/browse/PARQUET-1851). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Junjie Chen](https://issues.apache.org/jira/browse/PARQUET-1851?#comment-17153278) / @chenjunjiedada:
This is due to the client didn't write data successfully.

**Comment by asfimport** [comment]
[Junjie Chen](https://issues.apache.org/jira/browse/PARQUET-1851?#comment-17242217) / @chenjunjiedada:
Even the client doesn't write data, we should not throw NPE.

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1851?#comment-17262519) / @gszadovszky:
I would not agree. An empty row group shall never be written. NPE might not be the best thing the library could do but `ParquetMetadataConverer` is a low level implementation and not part of the public API so it is not required to handle these edge cases separately. I think, this issue should be handled at a higher level. Based on the stack trace this is in `ParquetFileWriter`. It should not allow writing an empty row group.
