### ISSUE TITLE
Avoid Copy of Bytes in Protobuf BinaryWriter

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2527]
```java

  class BinaryWriter extends FieldWriter {
    @Override
    final void writeRawValue(Object value) {
      ByteString byteString = (ByteString) value;
      Binary binary = Binary.fromConstantByteArray(byteString.toByteArray());
      recordConsumer.addBinary(binary);
    }
  }
```

`toByteArray()` creates a copy of the buffer.  There is already support with Parquet and Protobuf to pass instead a ByteBuffer which avoids the copy.

**Reporter**: [David Mollitor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=belugabehr) / @belugabehr
**Assignee**: [David Mollitor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=belugabehr) / @belugabehr
#### Related issues:
- [Move Support for ByteBuffer into TTransport](https://issues.apache.org/jira/browse/THRIFT-5288) (is blocked by)

<sub>**Note**: *This issue was originally created as [PARQUET-1918](https://issues.apache.org/jira/browse/PARQUET-1918). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[David Mollitor](https://issues.apache.org/jira/browse/PARQUET-1918?#comment-17206414) / @belugabehr:
Unit tests fail with:

 

Trying to address with THRIFT-5288

 
```java

java.lang.Exception: java.nio.ReadOnlyBufferException
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.nio.ReadOnlyBufferException
	at java.nio.ByteBuffer.array(ByteBuffer.java:996)
	at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.writeBinary(TCompactProtocol.java:375)
	at org.apache.parquet.format.InterningProtocol.writeBinary(InterningProtocol.java:135)
	at org.apache.parquet.format.ColumnIndex$ColumnIndexStandardScheme.write(ColumnIndex.java:945)
	at org.apache.parquet.format.ColumnIndex$ColumnIndexStandardScheme.write(ColumnIndex.java:820)
	at org.apache.parquet.format.ColumnIndex.write(ColumnIndex.java:728)
	at org.apache.parquet.format.Util.write(Util.java:372)
	at org.apache.parquet.format.Util.writeColumnIndex(Util.java:69)
	at org.apache.parquet.hadoop.ParquetFileWriter.serializeColumnIndexes(ParquetFileWriter.java:1087)
	at org.apache.parquet.hadoop.ParquetFileWriter.end(ParquetFileWriter.java:1050)
 
```
