### ISSUE TITLE
Merging parquet files created in 1.11.1 not possible using 1.12.0 

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2603]
I have parquet files created using 1.11.1. In the process I join two files (with the same schema) into a one output file. I create Hadoop writer:
```scala

val hadoopWriter = new ParquetFileWriter(
      HadoopOutputFile.fromPath(
        new Path(outputPath.toString),
        new Configuration()
      ), outputSchema, Mode.OVERWRITE,
      8 * 1024 * 1024,
      2097152,
      DEFAULT_COLUMN_INDEX_TRUNCATE_LENGTH,
      DEFAULT_STATISTICS_TRUNCATE_LENGTH,
      DEFAULT_PAGE_WRITE_CHECKSUM_ENABLED
    )
    hadoopWriter.start()
```
and try to append one file into another:
```scala

hadoopWriter.appendFile(HadoopInputFile.fromPath(new Path(file), new Configuration()))
```
Everything works on 1.11.1. But when I've switched to 1.12.0 it fails with that error:
```scala

STDERR: Exception in thread "main" java.io.IOException: can not read class org.apache.parquet.format.PageHeader: Required field 'uncompressed_page_size' was not found in serialized data! Struct: org.apache.parquet.format.PageHeader$PageHeaderStandardScheme@b91d8c4
 at org.apache.parquet.format.Util.read(Util.java:365)
 at org.apache.parquet.format.Util.readPageHeader(Util.java:132)
 at org.apache.parquet.format.Util.readPageHeader(Util.java:127)
 at org.apache.parquet.hadoop.Offsets.readDictionaryPageSize(Offsets.java:75)
 at org.apache.parquet.hadoop.Offsets.getOffsets(Offsets.java:58)
 at org.apache.parquet.hadoop.ParquetFileWriter.appendRowGroup(ParquetFileWriter.java:998)
 at org.apache.parquet.hadoop.ParquetFileWriter.appendRowGroups(ParquetFileWriter.java:918)
 at org.apache.parquet.hadoop.ParquetFileReader.appendTo(ParquetFileReader.java:888)
 at org.apache.parquet.hadoop.ParquetFileWriter.appendFile(ParquetFileWriter.java:895)
 at [...]
Caused by: shaded.parquet.org.apache.thrift.protocol.TProtocolException: Required field 'uncompressed_page_size' was not found in serialized data! Struct: org.apache.parquet.format.PageHeader$PageHeaderStandardScheme@b91d8c4
 at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1108)
 at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1019)
 at org.apache.parquet.format.PageHeader.read(PageHeader.java:896)
 at org.apache.parquet.format.Util.read(Util.java:362)
 ... 14 more
```

**Reporter**: [Matthew M](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eltherion)
**Assignee**: [Gabor Szadovszky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gszadovszky) / @gszadovszky

<sub>**Note**: *This issue was originally created as [PARQUET-2027](https://issues.apache.org/jira/browse/PARQUET-2027). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Matthew M](https://issues.apache.org/jira/browse/PARQUET-2027?#comment-17332009):
@gszadovszky Thank you for your work here! Any chances to get 0.12.1 released soon with that fix included?

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-2027?#comment-17332052) / @gszadovszky:
`[~eltherion]`, currently, I don't have the bandwidth to create another release. And, there might be other candidates as well. But, I'll create a branch and backport this one so if we create one it'll part of it.

**Comment by asfimport** [comment]
[Matthew M](https://issues.apache.org/jira/browse/PARQUET-2027?#comment-17332057):
Understood, thank you!(y)

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-2027?#comment-17332386) / @gszadovszky:
I've created the branch parquet-1.12.x and backported this change. Until we create the release 1.12.1 you may build and use your own version.
