### ISSUE TITLE
crypto exception in print toPrettyJSON

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2656]
In debug mode, this code 
`if (LOG.isDebugEnabled()) {`
`  LOG.debug(ParquetMetadata.toPrettyJSON(parquetMetadata));`
``}
called in `org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata()`

 

_\*in encrypted files with plaintext footer\*_ 

triggers an exception:

 
`Caused by: org.apache.parquet.crypto.ParquetCryptoRuntimeException: [id]. Null File Decryptor     `

`    at org.apache.parquet.hadoop.metadata.EncryptedColumnChunkMetaData.decryptIfNeeded(ColumnChunkMetaData.java:602) ~[parquet-hadoop-1.12.0jar:1.12.0]`
`    at org.apache.parquet.hadoop.metadata.ColumnChunkMetaData.getEncodingStats(ColumnChunkMetaData.java:353) ~[parquet-hadoop-1.12.0jar:1.12.0]`
`    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]`
`    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]`
`    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]`
`    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1516) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1217) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at shaded.parquet.com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1059) ~[parquet-jackson-1.12.0jar:1.12.0]`
`    at org.apache.parquet.hadoop.metadata.ParquetMetadata.toJSON(ParquetMetadata.java:68) ~[parquet-hadoop-1.12.0jar:1.12.0]`
`    ... 23 more`

**Reporter**: [Gidon Gershinsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gershinsky) / @ggershinsky
**Assignee**: [Gidon Gershinsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gershinsky) / @ggershinsky

<sub>**Note**: *This issue was originally created as [PARQUET-2103](https://issues.apache.org/jira/browse/PARQUET-2103). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-2103?#comment-17447372) / @ggershinsky:
@gszadovszky [~shangx@uber.com] will appreciate getting your advise on the solution options (here or at the sync call). This seems to be a print with a blind reflection loop, that calls all nested classes / methods in an object. Since v1.12.0, there is a EncryptedColumnChunkMetaData class inside the ColumnChunkMetaData. Creating its instance and calling the "decrypt" method is not a good idea, for either unencrypted or encrypted files.

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-2103?#comment-17447455) / @gszadovszky:
I think, we need to update [ParquetMetadata.toJSON](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/metadata/ParquetMetadata.java#L67-L71). Jackson shall be able to be configured to not to look for getter methods but the private fields. I am not sure if it is a good idea or if it will work in every environment. Another option would be to refactor EncryptedColumnChunkMetaData to not to call "decrypt" for a getter but it might not worth the efforts. The easiest way would be to simply detect if the metadata contains encrypted data and do not log anything. I don't know how urgent might it be to log the metadata in case of debugging.

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-2103?#comment-17448596) / @ggershinsky:
@gszadovszky thanks for pointing in the right direction. We can check that a file is encrypted, and then skip printing its column metadata - this solves the problem at hand. We will still be able to print the file-wide metadata (as opposed to the per-column metadata, which is encrypted with column-specific keys). I'll start working on a patch.
