### ISSUE TITLE
parquet-cli without hadoop throws java.lang.NoSuchMethodError on any parquet file access command

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2680]
I can't do even basic things with parquet-cli from 1.13.0-SNAPSHOT.

Steps to reproduce:
```

git clone <parquet-mr repo> 
cd parquet-mr
mvn clean install -DskipTests
cd parquet-cli
mvn clean install -DskipTests
mvn dependency:copy-dependencies
java -cp 'target/*:target/dependency/*' org.apache.parquet.cli.Main cat <parquet file>
```
Results:
```

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.parquet.avro.AvroSchemaConverter.convert(Lorg/apache/parquet/schema/MessageType;)Lorg/apache/avro/Schema;
    at org.apache.parquet.cli.util.Schemas.fromParquet(Schemas.java:89)
    at org.apache.parquet.cli.BaseCommand.getAvroSchema(BaseCommand.java:405)
    at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:66)
    at org.apache.parquet.cli.Main.run(Main.java:157)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
    at org.apache.parquet.cli.Main.main(Main.java:187)
```

**Environment**: Amazon Linux 2, Java 8
**Reporter**: [Timothy Miller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=theosib-amazon) / @theosib-amazon
**Assignee**: [Kengo Seki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sekikn) / @sekikn

<sub>**Note**: *This issue was originally created as [PARQUET-2142](https://issues.apache.org/jira/browse/PARQUET-2142). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2142?#comment-17527556) / @theosib-amazon:
I added -verbose:class to the java command line, and I found this in the output:
```

[Loaded org.apache.parquet.avro.AvroSchemaConverter from file:/local/home/theosib/packages/PARQUET-2140/parquet-mr/parquet-cli/target/parquet-cli-1.13.0-SNAPSHOT-runtime.jar] 
```
This isn't correct. It should be loading AvroSchemaConverter from target/dependency/parquet-avro-1.13.0-SNAPSHOT.jar. Evidently the instructions are wrong. I changed the run command to this:
```

java -cp 'target/parquet-cli-1.13.0-SNAPSHOT.jar:target/dependency/*' org.apache.parquet.cli.Main cat ~/guid.parquet
```
And the NoSuchMethodError went away. Now I get the Unknown error and java.lang.RuntimeException that we see in PARQUET-2143.

**Comment by asfimport** [comment]
[Balaji K](https://issues.apache.org/jira/browse/PARQUET-2142?#comment-17527714):
I see your environment is Linux. Feels like a dupe of https://issues.apache.org/jira/browse/PARQUET-2104 . Parquet-cli is broken on linux afaik.

**Comment by asfimport** [comment]
[Kengo Seki](https://issues.apache.org/jira/browse/PARQUET-2142?#comment-17585059) / @sekikn:
I also came across this issue. As @theosib-amazon pointed out, parquet-cli-$PROJECT_VERSION-runtime.jar contains the same class as parquet-cli-$PROJECT_VERSION.jar with a different method signature, due to [the relocation of the org.apache.avro package](https://github.com/apache/parquet-mr/blob/apache-parquet-1.12.3/parquet-cli/pom.xml#L201-L206).

```Java

$ unzip target/parquet-cli-1.13.0-SNAPSHOT-runtime.jar org/apache/parquet/avro/AvroSchemaConverter.class
Archive:  target/parquet-cli-1.13.0-SNAPSHOT-runtime.jar
  inflating: org/apache/parquet/avro/AvroSchemaConverter.class  
$ javap -c org.apache.parquet.avro.AvroSchemaConverter

...

  public org.apache.parquet.schema.MessageType convert(shaded.parquet.org.apache.avro.Schema);

...

  public shaded.parquet.org.apache.avro.Schema convert(org.apache.parquet.schema.MessageType);

...
```

I'll submit a documentation fix to notifying users not to include unnecessary jars when running parquet-cli without Hadoop.
