### ISSUE TITLE
parquet-cli with hadoop throws java.lang.RuntimeException on any parquet file access

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2681]
I can't do even basic things with parquet-cli from 1.13.0-SNAPSHOT.
```

git clone <parquet-mr repo> 
cd parquet-mr
mvn clean install -DskipTests
cd parquet-cli
mvn clean install -DskipTests
cd target
hadoop jar parquet-cli-1.13.0-SNAPSHOT-runtime.jar org.apache.parquet.cli.Main cat <parquet file>
```
Results:
```

Unknown error
java.lang.RuntimeException: Failed on record 0
    at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:86)
    at org.apache.parquet.cli.Main.run(Main.java:157)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
    at org.apache.parquet.cli.Main.main(Main.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
Caused by: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file file:/home/theosib/guid.parquet
    at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:264)
    at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)
    at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:136)
    at org.apache.parquet.cli.BaseCommand$1$1.advance(BaseCommand.java:363)
    at org.apache.parquet.cli.BaseCommand$1$1.<init>(BaseCommand.java:344)
    at org.apache.parquet.cli.BaseCommand$1.iterator(BaseCommand.java:342)
    at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:73)
    ... 9 more
Caused by: org.apache.parquet.io.ParquetDecodingException: The requested schema is not compatible with the file schema. incompatible types: required binary Number (STRING) != required fixed_len_byte_array(16) Number (UUID)
    at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.incompatibleSchema(ColumnIOFactory.java:101)
    at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.visit(ColumnIOFactory.java:93)
    at org.apache.parquet.schema.PrimitiveType.accept(PrimitiveType.java:602)
    at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.visitChildren(ColumnIOFactory.java:83)
    at org.apache.parquet.io.ColumnIOFactory$ColumnIOCreatorVisitor.visit(ColumnIOFactory.java:57)
    at org.apache.parquet.schema.MessageType.accept(MessageType.java:55)
    at org.apache.parquet.io.ColumnIOFactory.getColumnIO(ColumnIOFactory.java:162)
    at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:140)
    at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:230)
    ... 15 more
```

**Environment**: Amazon Linux 2, Java 8, Hadoop 3.2.3
**Reporter**: [Timothy Miller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=theosib-amazon) / @theosib-amazon

<sub>**Note**: *This issue was originally created as [PARQUET-2143](https://issues.apache.org/jira/browse/PARQUET-2143). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2143?#comment-17527558) / @theosib-amazon:
I didn't notice this earlier, but the ParquetDecodingException is the same as what's shown in PARQUET-2140. We may want to resolve PARQUET-2143 as a duplicate of that.

**Comment by asfimport** [comment]
[Balaji K](https://issues.apache.org/jira/browse/PARQUET-2143?#comment-17527709):
[EDIT]: never mind, i missed seeing the decoding exception. Yes, that would make this a dupe of https://issues.apache.org/jira/browse/PARQUET-2140

[original comment]I see your environment is Linux. Feels like a dupe of https://issues.apache.org/jira/browse/PARQUET-2104 . Parquet-cli is broken on linux afaik.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2143?#comment-17540143) / @theosib-amazon:
There's a slight chance that <https://github.com/apache/parquet-mr/pull/957> might fix this. I'll have to try this out later.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2143?#comment-17542998) / @theosib-amazon:
I tested PR #957 on this, and it doesn't fix the problem. So they're unrelated. This is just a mismatch between some duplicated code in the CLI and other code elsewhere.
