### ISSUE TITLE
Cannot read schema from parquet file

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2690]
I'm trying to generate a Avro schema from a parquet file. I get the issue both when using <https://github.com/benwatson528/intellij-avro-parquet-plugin> in Intellij as well as when I'm using my own implementation of generating a schema. 

The parquet file contains nested entries and arrays: \{"a": a, "b": [{"c": c}]}

I get the following error message: 
```java

org.apache.avro.SchemaParseException: Can't redefine: element
    at org.apache.avro.Schema$Names.put(Schema.java:1547)
    at org.apache.avro.Schema$NamedSchema.writeNameRef(Schema.java:810)
    at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:972)
    at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1239)
    at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:1000)
    at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:984)
    at org.apache.avro.Schema$ArraySchema.toJson(Schema.java:1134)
    at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1239)
    at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:1000)
    at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:984)
    at org.apache.avro.Schema$UnionSchema.toJson(Schema.java:1239)
    at org.apache.avro.Schema$RecordSchema.fieldsToJson(Schema.java:1000)
    at org.apache.avro.Schema$RecordSchema.toJson(Schema.java:984)
    at org.apache.avro.Schema.toString(Schema.java:424)
    at org.apache.avro.Schema.toString(Schema.java:396)
    at uk.co.hadoopathome.intellij.viewer.fileformat.ParquetFileReader.getSchema(ParquetFileReader.java:65)
    at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:196)
    at uk.co.hadoopathome.intellij.viewer.FileViewerToolWindow$2.doInBackground(FileViewerToolWindow.java:184)
    at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829) 
```

It appears to be an issue similar to [PARQUET-1441](https://issues.apache.org/jira/browse/PARQUET-1441) or [PARQUET-1409](https://issues.apache.org/jira/browse/PARQUET-1409).

Or could it possibly be something wrong in my parquet file?

**Reporter**: [Nils Broman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nils.scila)

<sub>**Note**: *This issue was originally created as [PARQUET-2153](https://issues.apache.org/jira/browse/PARQUET-2153). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Nils Broman](https://issues.apache.org/jira/browse/PARQUET-2153?#comment-17553555):
I found out that this is indeed the same issue as for PARQUET-1441, however for FixedSchema. The fix is isolated to RecordSchema and the same fix needs to be applied to FixedSchema as well.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2153?#comment-17553635) / @theosib-amazon:
Is this related to anything fixed by <https://github.com/apache/parquet-mr/pull/957> ?

**Comment by asfimport** [comment]
[Nils Broman](https://issues.apache.org/jira/browse/PARQUET-2153?#comment-17554037):
I just tested the fix you mention and I still got the same error, so unfortunately it does not fix this issue.
