### ISSUE TITLE
Infinite recursion in AvroSchemaConverter

### ISSUE THREAD

**Issue by gauravkhatri05** [apache/parquet-java#2961]
### Describe the bug, including details regarding any error messages, version, and platform.

**Issue:**  I am trying to write Parquet file using S3SinkConnector and when it tries to convert avro schema using a method `AvroSchemaConverter.convert(Schema avroSchema)` it enters into the infinite recursion.

Please refer to link below for the problematic code:
https://github.com/apache/parquet-java/blob/1de2af8b8b7dc86af120da7c0ce3e43453ea98dc/parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java#L147C3-L163C4

**Details**
Please find the schema which has nested recursive reference (ObjXX.struct_add_list.fld_list.ref_val.fld_list.ref_val...) that is being parsed:
`
{
  "type": "record",
  "name": "ObjXX",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "struct_add_list",
      "type": [
        "null",
        {
          "type": "array",
          "items": [
            "null",
            {
              "type": "record",
              "name": "ObjStructAdd",
              "fields": [
                {
                  "name": "name",
                  "type": [
                    "null",
                    "string"
                  ],
                  "default": null
                },
                {
                  "name": "fld_list",
                  "type": [
                    "null",
                    {
                      "type": "array",
                      "items": [
                        "null",
                        {
                          "type": "record",
                          "name": "ObjStructAddFld",
                          "fields": [
                            {
                              "name": "name",
                              "type": [
                                "null",
                                "string"
                              ],
                              "default": null
                            },
                            {
                              "name": "ref_val",
                              "type": [
                                "null",
                                "ObjStructAdd"
                              ],
                              "default": null
                            }
                          ]
                        }
                      ]
                    }
                  ],
                  "default": null
                }
              ]
            }
          ]
        }
      ],
      "default": null
    },
    {
      "name": "kafka_offset",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "kafka_partition",
      "type": [
        "null",
        "int"
      ],
      "default": null
    },
    {
      "name": "kafka_timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "kafka_key",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "headers",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
`

Please find below stack-trace:

`[task-thread-parquet-sink-connector-0] ERROR org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=parquet-sink-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: null
java.lang.StackOverflowError
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:196)
	at org.apache.parquet.avro.AvroSchemaConverter.convertUnion(AvroSchemaConverter.java:268)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:224)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:166)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:207)
	at org.apache.parquet.avro.AvroSchemaConverter.convertUnion(AvroSchemaConverter.java:268)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:224)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:166)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:287)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:160)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:196)
	at org.apache.parquet.avro.AvroSchemaConverter.convertUnion(AvroSchemaConverter.java:268)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:224)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:166)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:287)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:160)`

Could you please look into this. thanks :-)

**Comment by gauravkhatri05** [comment]
Hello Arnav, Thanks for the reply. Yes max depth is the only way to control the infinite recursion, we also have patched locally by same technique. But it is always good to have patch at library level.

One request, make this max depth configurable because I have found below 8 it doesn't work properly and if we keep max depth too high then it also impacts the performance. 10 is the ideal but if you can make configurable it will be awesome.

> Hi @gauravkhatri05, avro recursion is not supported. I'll raise a patch to control this through a max recursion depth
