### ISSUE TITLE
Cannot read parquet file that was generated from nanoparquet

### ISSUE THREAD

**Issue by RealTYPICAL** [apache/parquet-java#3043]
### Describe the bug, including details regarding any error messages, version, and platform.

When trying to use `MessageColumnIO` to get a record reader, the following error occurs:
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.apache.parquet.column.values.ValuesReader.readInteger(ValuesReader.java:178)
	at org.apache.parquet.column.impl.ColumnReaderBase$ValuesReaderIntIterator.nextInt(ColumnReaderBase.java:830)
	at org.apache.parquet.column.impl.ColumnReaderBase.checkRead(ColumnReaderBase.java:663)
	at org.apache.parquet.column.impl.ColumnReaderBase.consume(ColumnReaderBase.java:801)
	at org.apache.parquet.column.impl.ColumnReaderImpl.consume(ColumnReaderImpl.java:30)
	at org.apache.parquet.column.impl.ColumnReaderImpl.<init>(ColumnReaderImpl.java:43)
	at org.apache.parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:80)
	at org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:282)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:141)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:105)
	at org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:180)
	at org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:105)
```

I expected that this would work. Pyarrow for example can read the file.

Sample file can be found here: 

[mtcars_np.zip](https://github.com/user-attachments/files/17649331/mtcars_np.zip)

Nanoparquet can be found here:

https://github.com/r-lib/nanoparquet

Version: 1.14.3
Platform: Linux

### Component(s)

Core

**Comment by wgtmac** [comment]
Thanks for reporting this issue! I can confirm that it has been reproduced on my side. Will take a look later.

**Comment by SourabhBadhya** [comment]
The following issue is still reproducible in the current release version on the same example file. I tried investigating the issue - Here are some of my observations.
The pages are written DataPageV1 format, which seems to be precursor version to DataPageV2. 
The failure seems to happen when the pages for the first column is read - 
Column - `{"PathInSchema":["Rowname"],"Type":"BYTE_ARRAY","Encodings":["PLAIN"],"CompressedSize":448,"UncompressedSize":528,"NumValues":32,"CompressionCodec":"SNAPPY"}`
While reading through the pages, it creates `repetitionLevelColumn` and `definitionLevelColumn` as `ValuesReaderIntIterator`. However, when it actually tries to get the next integer for the iteration using `ValuesReaderIntIterator`, it tries to call the `BinaryPlainValuesReader#readInteger()` which is not defined for BinaryPlainValuesReader, which is why its failing. Currently its only defined for `IntegerPlainValuesReader`.

This is just one instance wherein its failing. I am assuming similar error behaviour for other datatypes apart from Integer for the Plain encoding.

@wgtmac I am wondering how should we calculate the nextInt() for the different datatypes, since there does not seem to be a way to that right now. Should we maintain a variable to keep track of the index when it tries to read/skip from ByteBufferInputStream and then provide the same index for the `ValuesReaderIntIterator`.

I am also trying to understand what does `repetitionLevelColumn` and `definitionLevelColumn` exactly mean and how are they used for read / skip the incoming data?
