### ISSUE TITLE
`ParquetMetadata` JSON serialization is failing

### ISSUE THREAD

**Issue by Fokko** [apache/parquet-java#3086]
### Describe the bug, including details regarding any error messages, version, and platform.

Discovered by plugging in RC1 into Spark: https://github.com/apache/spark/pull/48970

Failing test: https://github.com/Fokko/spark/actions/runs/12027509812/job/33528737000
```
...
Cause: java.lang.RuntimeException: shaded.parquet.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.apache.parquet.schema.LogicalTypeAnnotation$StringLogicalTypeAnnotation and no properties discovered to create BeanSerializer 
    (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) 
    (through reference chain: org.apache.parquet.hadoop.metadata.ParquetMetadata["fileMetaData"]->org.apache.parquet.hadoop.metadata.FileMetaData["schema"]->org.apache.parquet.schema.MessageType["fields"]->java.util.ArrayList[1]->org.apache.parquet.schema.PrimitiveType["logicalTypeAnnotation"])
  at org.apache.parquet.hadoop.metadata.ParquetMetadata.toJSON(ParquetMetadata.java:73)
  at org.apache.parquet.hadoop.metadata.ParquetMetadata.toPrettyJSON(ParquetMetadata.java:49)
  at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1594)
...
```

I checked the affected classes, and they haven't changed for a long time, so I believe it is the upgrade to the later version of Jackson. Spark uses the same version of Jackson, so I fixed it by allowing to serialize to `null`.

Converting to JSON is used for debugging purposes: 

https://github.com/apache/parquet-java/blob/7644e27717e09d570d99f76cf5bb631122d374bf/parquet-hadoop/src/main/java/org/apache/parquet/format/converter/ParquetMetadataConverter.java#L1594

**Comment by Fokko** [comment]
This one has been fixed already, forgot to close it.
